### ISSUE TITLE
Funktionalität PV Überschussladen

### ISSUE THREAD

**Issue by Trunks1982** [MK-2001/ioBroker.go-e#1]
Hi ich könnte dir mit einem Script weiterhelfen was man vielleicht mit einbauen könnte.Dieses holt die Werte von meinem Wechselrichter und berechnet danach wieviel das Auto laden darf.

**Comment by MK-2001** [comment]
Okay. Gerne. Da es sich um einen Adapter für go-e handelt und nicht jeder eine Photovoltaik daheim hat, könnte ich mir eine Funktion erstellen, welche z.B. beim nächsten Laden die maximale Menge zulässt. 

Kannst du den Anwendungsfall genauer in Einzelschritten mit einem Beispiel beschreiben?

**Comment by Trunks1982** [comment]
let timeout;
/************************************* Debug / Logging ***********************************************/
let logging = false;
let debug = false;
let force = false;

/************************************* Vor dem Star anpassen ***********************************************/
// Bitte die Instanz auswählen

// const preafix = '0_userdata.0';
// oder
const preafix = 'javascript.0';
//---------------------------------//
const ueberschussDp = 'smartmeter.0.1-0:16_7_0__255.value';
const voltDP = 'javascript.0.go_echarger.nrg0';
const ladenOn = 'javascript.0.go_echarger.nrg11'
/************************************* Variablen ***********************************************/

let ampere = [
    /* bei 224 Volt
    Stuffe 1 : 1344 W, Stuffe 2 : 1792 W, Stuffe 3 : 2240 W, Stuffe 4 : 2688 W, Stuffe 5 : 3136 W, Stuffe 6 : 3584 W, Stuffe 7 : 4032 W, 
    Stuffe 8 : 4480 W, Stuffe 9 : 4928 W, Stuffe 10 : 5376 W, Stuffe 11 : 5824 W, Stuffe 12 : 6272 W, Stuffe 13 : 6720 W, Stuffe 14 : 7168 W
    */
    6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32
];


let Stuffe = null;
let oldWatt = null;
let newWatt = null;
let ladenStatus = false;
let oldState = null;
let differenz = null;
let ueberschuss = getState(ueberschussDp).val;
let volt = getState(voltDP).val;
let laden = null;
let test6 = null 
sendState(6)
/******************************************************* berechnung des Ladestrom  functions ***************************************************************************/

function chargeLevel() {

    ueberschuss = getState(ueberschussDp).val;


    if (debug) console.log('Überschuss: ' + ueberschuss);

    /* berechnung der Ladestrom Stufe */
  


        if (ueberschuss >= 0) {


            if (debug) console.log('ladenStatus ' + ladenStatus);

            if (ueberschuss >= 0 && Stuffe <= 14 + 1 && Stuffe >= 0 - 1) {

                Stuffe = (Stuffe - 1);

                if (logging) console.log('Stuffe: ' + Stuffe);

            }

        }


      //if (ueberschuss < 0 && ladenStatus == true || oldState > ueberschuss || Stuffe === 0 ) {
    if (ueberschuss < 0 ) {
var test6 = getState('javascript.0.go_echarger.nrg11').val * 1000 - 200;

            oldState = ueberschuss;

            if (logging) console.log('oldState: ' + oldState);

            ladenStatus = false;

            if (logging) console.log(ladenStatus);

            var ueberschuss = Math.abs(getState(ueberschussDp).val);
            
            var ueberschuss_new = (test6 + ueberschuss)

//log (ueberschuss_new, 'warn')

            if (debug) console.log(' ' + ueberschuss);

            if (debug) console.log('ladenStatus ' + ladenStatus);

            oldWatt = ueberschuss;

timeout = setTimeout(function () {

            if (ueberschuss_new >= 0 && ueberschuss_new <= (ampere[0] * volt)) {

                Stuffe = 1;

                if (logging) console.log('Stuffe: ' + Stuffe);

           

            } else if (ueberschuss_new >= (ampere[1] * volt - ((ampere[1] * volt) - (ampere[0] * volt))) && ueberschuss_new <= ampere[1] * volt) {

                Stuffe = 2;

                

                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[2] * volt - ((ampere[2] * volt) - (ampere[1] * volt))) && ueberschuss_new <= ampere[2] * volt) {

                Stuffe = 3;
    

                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[3] * volt - ((ampere[3] * volt) - (ampere[2] * volt))) && ueberschuss_new <= ampere[3] * volt) {

            Stuffe = 4;

                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[4] * volt - ((ampere[4] * volt) - (ampere[3] * volt))) && ueberschuss_new <= ampere[4] * volt) {

                Stuffe = 5;

          

                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[5] * volt - ((ampere[5] * volt) - (ampere[4] * volt))) && ueberschuss_new <= ampere[5] * volt) {

                Stuffe = 6;

            

                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[6] * volt - ((ampere[6] * volt) - (ampere[5] * volt))) && ueberschuss_new <= ampere[6] * volt) {

                Stuffe = 7;

       

                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[7] * volt - ((ampere[7] * volt) - (ampere[6] * volt))) && ueberschuss_new <= ampere[7] * volt) {

                Stuffe = 8;


                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[8] * volt - ((ampere[8] * volt) - (ampere[7] * volt))) && ueberschuss_new <= ampere[8] * volt) {

                Stuffe = 9;

                
                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[9] * volt - ((ampere[9] * volt) - (ampere[8] * volt))) && ueberschuss_new <= ampere[9] * volt) {

                Stuffe = 10;

                

                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[10] * volt - ((ampere[10] * volt) - (ampere[9] * volt))) && ueberschuss_new <= ampere[10] * volt) {

                Stuffe = 11;

               

                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[11] * volt - ((ampere[11] * volt) - (ampere[10] * volt))) && ueberschuss_new <= ampere[11] * volt) {

                Stuffe = 12;
            
                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[12] * volt - ((ampere[12] * volt) - (ampere[11] * volt))) && ueberschuss_new <= ampere[12] * volt) {

                Stuffe = 13;
       
                if (logging) console.log('Stuffe: ' + Stuffe);

            } else if (ueberschuss_new >= (ampere[13] * volt - ((ampere[13] * volt) - (ampere[12] * volt))) && ueberschuss_new <= ampere[13] * volt) {

                Stuffe = 14;
               
                if (logging) console.log('Stuffe: ' + Stuffe);

            }
             }, 15000);
        }
       
}

function test3() {


    if (Stuffe === 0) {

        if (logging) console.log('Laden Aus')

        if (logging) console.log('Laden Aus');

    } else if (Stuffe === 1) {

        if (logging) console.log(ueberschuss + ' w')

        if (logging) console.log(ampere[0] + ' A');
        sendState(ampere[0]);
    } else if (Stuffe === 2) {

        if (logging) console.log(ueberschuss + ' w')

        if (logging) console.log(ampere[1] + ' A ');
        sendState(ampere[1]);
    } else if (Stuffe === 3) {

        if (logging) console.log(ueberschuss + ' w')

       if (logging)  console.log(ampere[2] + ' A ');
        sendState(ampere[2]);
    } else if (Stuffe === 4) {

        if (logging) console.log(ueberschuss + ' w')

       if (logging)  console.log(ampere[3] + ' A ');
        sendState(ampere[3]);
    } else if (Stuffe === 5) {

        if (logging) console.log(ueberschuss + ' w')

       if (logging)  console.log(ampere[4] + ' A ');
        sendState(ampere[4]);
    } else if (Stuffe === 6) {

        if (logging) console.log(ueberschuss + ' w')

        if (logging) console.log(ampere[5] + ' A ');
        sendState(ampere[5]);
    } else if (Stuffe === 7) {

        if (logging) console.log(ueberschuss + ' w')

       if (logging) console.log(ampere[6] + ' A ');
        sendState(ampere[6]);
    } else if (Stuffe === 8) {

        if (logging) console.log(ueberschuss + ' w')

       if (logging)  console.log(ampere[7] + ' A ');
        sendState(ampere[7]);
    } else if (Stuffe === 9) {

        if (logging) console.log(ueberschuss + ' w')

       if (logging)  console.log(ampere[8] + ' A ');
        sendState(ampere[8]);
    } else if (Stuffe === 10) {

        if (logging) console.log(ueberschuss + ' w')

       if (logging)  console.log(ampere[9] + ' A ');
        sendState(ampere[9]);
    } else if (Stuffe === 11) {

        if (logging) console.log(ueberschuss + ' w')

        if (logging) console.log(ampere[10] + ' A ');
        sendState(ampere[10]);
    } else if (Stuffe === 12) {

        if (logging) console.log(ueberschuss + ' w')

        if (logging) console.log(ampere[11] + ' A ');
        sendState(ampere[11]);
    } else if (Stuffe === 13) {

        if (logging) console.log(ueberschuss + ' w')

       if (logging)  console.log(ampere[12] + ' A ');
        sendState(ampere[12]);
    } else if (Stuffe === 14) {

       if (logging)  console.log(ampere[13] + ' A ');

        if (logging) console.log(ueberschuss + ' W');
        sendState(ampere[13]);
    }

}


function sendState(text) {
    if (debug) log(text)
    setState('javascript.0.go_echarger.write_amp', text, false);
}


/************************************* Trigger ***********************************************/

on({ id: ueberschussDp, change: 'any' }, function (obj) {
    newWatt = Math.abs(obj.state.val);
    oldWatt = Math.abs(obj.oldState.val);
    chargeLevel();
    test3();
});

on({ id: ueberschussDp, change: 'any' }, function (obj) {
    volt = getState(voltDP).val;
});

on({ id: ladenOn, change: 'ne' }, function (obj) {
    laden = obj.state.val
    if (laden == 0) {
        ladenStatus = false
        if (logging) console.log('The vehicle has started charging')
    }
});







Dieses script steuert die Lademenge nach PV Leistung.Meine Vorstellung war, das man es zb im Adapter mit einem Päckchen anwählbar macht.So kann jeder deiner PV Anlage oder eben auch keine hat nach seinen wünschen den Adapter nutzen.

**Comment by Dreistein19** [comment]
Moin,
meint ihr nicht das, genau das Überschuss Laden oder Heizen mit PV die Aufgabe von ioBroker ist ?
Ich denke eine solch spezielle Funktion gehört nicht in einen Adpater.
Der Adpater sollte nur die Daten eines Devices auf eine Art aufbereiten und in Datenpunkte schreiben die der User dann mit
Java oder Blockly weiter verarbeiten kann.
Viel Erfolg beim Entwickeln. Mein goE wartet im Carport. Noch leider ohne WLan ...

**Comment by Trunks1982** [comment]
> Moin,
> meint ihr nicht das, genau das Überschuss Laden oder Heizen mit PV die Aufgabe von ioBroker ist ?
> Ich denke eine solch spezielle Funktion gehört nicht in einen Adpater.
> Der Adpater sollte nur die Daten eines Devices auf eine Art aufbereiten und in Datenpunkte schreiben die der User dann mit
> Java oder Blockly weiter verarbeiten kann.
> Viel Erfolg beim Entwickeln. Mein goE wartet im Carport. Noch leider ohne WLan ...

Moin,
Ich finde genau das gehört da rein aber natürlich zum abwählen.Hat ja nicht jeder eine PV Anlage.Aber genau das machts ja erst interessant😉.

**Comment by Dreistein19** [comment]
Gehört hier nicht her, weil kein Forum : https://www.youtube.com/watch?v=jC1-T8tF83s
Das könnte deine Lösung sein.

**Comment by Trunks1982** [comment]
Wieso ich hab ne lösung und die funktioniert super mit dem Adapter.

**Comment by MK-2001** [comment]
Hallo @Dreistein19 , danke für deine Anmerkungen und ich gebe dir völlig recht. Der HW-Adapter hat
bereits eine Ladestrombegrenzung eingebaut. Diese werde ich auch zur Verfügung stellen. Ebenso werde ich die Möglichkeit schaffen, per Max_Ampere und Strombegrenzung solch eine Möglichkeit zu erstellen diese Funktionen zu nutzen.

Durch eine Angabe von max_watts wird entsprechend des Anschlusses der Strom begrenzt. Wie dies später somit stelle ich so wie du es vorschlägst nur Events und Punkte bereit um die HW zu steuern. Wie die Watt-Begrenzung auf den Wert gesetzt wird, muss der ioBroker mit seinem eigenen Script entscheiden. Aber ich würde Trunks1982 einige Zeilen Code abnehmen.

**Comment by MK-2001** [comment]
Das Video ist aber Schleichwerbung. Das ist zum einen nicht die einzige HW. Zum anderen auch lange nicht beste.

**Comment by MK-2001** [comment]
Durch Version 0.0.5 habe ich die Möglichkeit gegeben, dass man dem Script alle 30 Sekunden übergeben kann, wieviel Strom beladen werden darf. in Watt. 

https://github.com/MK-2001/ioBroker.go-e/pull/7

Das Script um nun die Aktualisierungen von deiner PV an den Adapter zu schreiben müsstest du noch selbst bauen. Aber das Script überprüft gerade, wieviele Phasen anliegen. Nimmt auch die anliegende Spannung zur Berechnung.

Alle Übermittlungen zwischen den 30 Sekunden werden verworfen. D.h. wenn es in einer von 30 Sekunden mal richtig die Sonne scheint, und danach eigentlich nur nacht ist, hast du leider mehr verbraucht, als du eingespeist hast. 
Kannst du bitte die Funktionalität testen? Ich habe keine PV-Analge und teste mit einem Dummy Script. Wenn die werte zu differenziert sind, kann ich auch noch aus den 30 Sekunden Werten einen Schnitt berechnen und diesen dann an den Adapter übergeben.

**Comment by Trunks1982** [comment]
Wie meinst die aktualisierung von pv zum adapter?

**Comment by Trunks1982** [comment]
> Durch Version 0.0.5 habe ich die Möglichkeit gegeben, dass man dem Script alle 30 Sekunden übergeben kann, wieviel Strom beladen werden darf. in Watt.
> 
> #7
> 
> Das Script um nun die Aktualisierungen von deiner PV an den Adapter zu schreiben müsstest du noch selbst bauen. Aber das Script überprüft gerade, wieviele Phasen anliegen. Nimmt auch die anliegende Spannung zur Berechnung.
> 
> Alle Übermittlungen zwischen den 30 Sekunden werden verworfen. D.h. wenn es in einer von 30 Sekunden mal richtig die Sonne scheint, und danach eigentlich nur nacht ist, hast du leider mehr verbraucht, als du eingespeist hast.
> Kannst du bitte die Funktionalität testen? Ich habe keine PV-Analge und teste mit einem Dummy Script. Wenn die werte zu differenziert sind, kann ich auch noch aus den 30 Sekunden Werten einen Schnitt berechnen und diesen dann an den Adapter übergeben.


Sehe jetzt nicht neues und weiß gerade nicht wo ich es hinschreiben soll.

**Comment by MK-2001** [comment]
Okay. Ich werde noch eine Doku für den Adapter erstellen. Da kann ich dann auch die Features beschreiben. 

Wenn ich das richtig aus deinem Script gelesen habe, lädst du dir hiermit  
`const ueberschussDp = 'smartmeter.0.1-0:16_7_0__255.value';`  
die Leistung, welche von deiner PV-Anlage kommt. 

Der große Teil der `stuffe` bearbeitet m.E. nur wie viel Ampere die Ladeleistung betragen darf, damit du weiterhin keinen zusätzlichen Strom aus der Dose ziehen musst.

Du müsstest nun nur ein Script schreiben, welches   
`smartmeter.0.1-0:16_7_0__255.value => go-e.0.maxWatts`  
schreibt.

**Comment by Trunks1982** [comment]
Wollte gerade schreiben das es bei mir nicht vorkommt.Das script ist ja einfach.Habs schon fertig

**Comment by MK-2001** [comment]
Oh je. 
Kommt nun im nächsten Commit. Man muss auch die große geschreibene Funktion aufrufen....
4f5e8bc9945782394acf9e677acf5c22f34b4659

**Comment by Trunks1982** [comment]
Wie lange dauert das?

**Comment by Trunks1982** [comment]
bekomme immer noch nicht die 0.0.6

**Comment by MK-2001** [comment]
Ich habe gerade keinen Zugriff an meinen Adapter, da ich den zur Reparatur einsenden musste daher kann ich nicht testen. Ich kann die Version freigeben, dann sollte aber auf die Protokolle Extrems geachtet werden. Da man schon schauen muss das sich keine Endlosschleife ergibt usw.

**Comment by Trunks1982** [comment]
von mir aus kann ja die alte version wieder einspielen

**Comment by Trunks1982** [comment]
Moin bekommste heute die neue Version hochgeladen?

**Comment by MK-2001** [comment]
Hi,

Die Version ist bereits im Git. Nur nicht als NPM eingestellt. Ich würde es gerne zuvor testen. Mein Go-eCharger kommt erst am Mittwoch aus der Reperaturbzurück. Nach dem erfolgreichen Test, erstelle ich dann auch das NPM Paket.

**Comment by Trunks1982** [comment]
Hi nehme immer nur das aus dem git.Hatte vorgestern mal installiert aber versions mässig hatte sich nichts getan

**Comment by Trunks1982** [comment]
> Hi,
> 
> Die Version ist bereits im Git. Nur nicht als NPM eingestellt. Ich würde es gerne zuvor testen. Mein Go-eCharger kommt erst am Mittwoch aus der Reperaturbzurück. Nach dem erfolgreichen Test, erstelle ich dann auch das NPM Paket.


Das funktioniert nicht.


<img width="2046" alt="Bildschirmfoto 2020-08-16 um 16 50 44" src="https://user-images.githubusercontent.com/62701386/90337117-b2950380-dfe0-11ea-9cf4-84d15da9b6f5.png">

**Comment by MK-2001** [comment]
=> https://github.com/MK-2001/ioBroker.go-e/tree/feature/maxWatts Version 0.0.6

**Comment by Trunks1982** [comment]
> => https://github.com/MK-2001/ioBroker.go-e/tree/feature/maxWatts Version 0.0.6

Gerade installiert bleibt bei 0.0.5.Und Änderung passiert auch nicht bei max watts

**Comment by Trunks1982** [comment]
> => https://github.com/MK-2001/ioBroker.go-e/tree/feature/maxWatts Version 0.0.6

Hast du denn wie oben auf dem screenshot auch auf Austria stehn?

**Comment by MK-2001** [comment]
Also Adapter ist angekommen und ich habe die Tests durchgeführt. 

Einen Fehler habe ich noch beim Laden bemerkt, wenn das Fahrzeug nur mit einer Phase lädt statt mit allen drei angeschlossenen. Dann wären 6 Ampere bei der einphasigen Ladung des Fahrzeugs natürlich nur ein drittel des Überschusses verbraucht. 

Das kommt dann in der Version 0.0.7 :-)

**Comment by Trunks1982** [comment]
> Also Adapter ist angekommen und ich habe die Tests durchgeführt.
> 
> Einen Fehler habe ich noch beim Laden bemerkt, wenn das Fahrzeug nur mit einer Phase lädt statt mit allen drei angeschlossenen. Dann wären 6 Ampere bei der einphasigen Ladung des Fahrzeugs natürlich nur ein drittel des Überschusses verbraucht.
> 
> Das kommt dann in der Version 0.0.7 :-)

Bis jetzt hab ich aber immer noch nicht die 0.0.6😭

**Comment by Trunks1982** [comment]
So hab jetzt die 0.0.6 drauf aber wenn ich ich in max watts was eingebe passiert unter amp nichts.

**Comment by Trunks1982** [comment]
So gerade habe ich rausgefunden wenn ich 2 eingebe lädt er mit 32 A und wenn ich 15 eingebe lädt er mit 15A.Also normal muss er doch wenn Überschuss 4000Watt hat mit ca 12 A laden.Irgendwas stimmt mit der Berechnung nicht.

**Comment by MK-2001** [comment]
Ja und nein. 
Ich hatte einen Fehler in der Berechnung, den habe ich nun korrigiert. 

Ich habe zudem mehr Debug informationen hinzugefügt. Ggf. kannst du dir die preview vom Git ziehen. 0.0.7

**Comment by Trunks1982** [comment]
> Ja und nein.
> Ich hatte einen Fehler in der Berechnung, den habe ich nun korrigiert.
> 
> Ich habe zudem mehr Debug informationen hinzugefügt. Ggf. kannst du dir die preview vom Git ziehen. 0.0.7

Nach erster Ansicht scheint es zu funktionieren.Morgen werde ich es live testen

**Comment by Trunks1982** [comment]
Eine Frage hab ich, versucht er immer alles voll auszuschöpfen oder hat er noch nen puffer von 200watt zb eingestellt

**Comment by MK-2001** [comment]
max watts stellt die maximalen Ampere anhand der Angabe von Watt ein.
energy.adjustAmpLevelInWatts ändert die derzeit verwendeten Watts durch das hinzufügen oder abziehen von dan angegeben watt.

Bsp. bei 3 Phasen mit je 6 A hast du 4140 Watt im Verbrauch. Wenn du nun weitere 2000 Watt freigeben möchtest, übergibst du 2000 in den State. wenn du 2000 Watt wieder weniger freistellen möchtest übergibst du -2000 dann wird wieder eingeschränkt.

TS habe ich leider nicht. Via Telegram aber hier:
https://t.me/eMKa2001

**Comment by oneill2612** [comment]
Man ist das kompliziert XD..
Ich habe erst neu mit den ioBroker angefangen und habe zuhause eine PV und den Go-Charger ich wollte mein Auto über PV Überschuss laden was genau muss ich da jetzt alles eintragen? Meine Daten bekomme ich über den Senec Addaper weil ich einen Senec speicher habe.

**Comment by MK-2001** [comment]
Hallo oneil2612 könnten wir den Support bitte in z.B. Telegram verschieben. Den Link findest du im Post zuvor. https://github.com/MK-2001/ioBroker.go-e/issues/1#issuecomment-683275890 

Du brauchst auf jedenfall einenen Status in dem der aktuelle Überschuss eingetragen ist.

**Comment by Trunks1982** [comment]
> Man ist das kompliziert XD..
> Ich habe erst neu mit den ioBroker angefangen und habe zuhause eine PV und den Go-Charger ich wollte mein Auto über PV Überschuss laden was genau muss ich da jetzt alles eintragen? Meine Daten bekomme ich über den Senec Addaper weil ich einen Senec speicher habe. Was auch cool wäre das man über VIS einen Knopf hat zum PV überschuss laden An/Aus welche Punkte aus den Adaper müsste man dafür nehme ?
> Mein Auto läd nur 1Phasig mit 3,7KW

Welches Auto lädt denn so dermassen langsam?
Ein Phasig kann auch bis 7200Watt gehn.

**Comment by oneill2612** [comment]
Fast alle Hybrid Autos laden leider solangsam aber das macht ja nix zursache

**Comment by Trunks1982** [comment]
Ne nicht wirklich hat mich aber interessiert😝

**Comment by oneill2612** [comment]
Das stimmt .

**Comment by MK-2001** [comment]
Ich glaube das Thema ist durch. Schein zu funktionieren. Doku ist nun auch da.
