### ISSUE TITLE
fehlermeldung im iobroker

### ISSUE THREAD

**Issue by luckyheiko** [MK-2001/ioBroker.go-e#104]
habe eine HW V2 mit SW V0.40 und bekomme diesen Fehler

API response validation error: [{"message":"\"tme\" with value \"0101-300152\" fails to match the required pattern: /^[0-9]{10}$/","path":["tme"],"type":"string.pattern.base","context":{"regex":{},"value":"0101-300152","label":"tme","key":"tme"}}]

ich starte das modul nur sehr selten, da ich zur zeit noch nicht so oft daheim laden muss.
heute ist mir aufgefallen, das ich diese fehlermeldung bekomme und leider gar nichts mit anfangen kann :(

liegt das an meinem Problem, das der Go-E laut FritzBox im WLan ist aber wenn ich in der App schaue steht immer Disconectet?

ausschnitt von meiner fritz box
WLAN-Eigenschaften (2,4 GHz)
Signalstärke-88dBm
max. mögliche Datenrate72 / 72 Mbit/s
aktuelle Datenrate1 / 2 Mbit/s
WLAN-StandardWLAN-b+g+n / Wi-Fi 4
Frequenzband2,4 GHz
Kanalbandbreite20 MHz
Streams1 x 1
WLAN-Eigenschaften
VerschlüsselungWPA2
SignaleigenschaftenSTBC
QoS (Quality of Service)
Repeaterbetriebnein

go-e.0.wifi.state = NO_CONNECTION

würde mich über eine kurze Info sehr freuen
mfg heiko

**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by MK-2001** [comment]
Ich müsste mal ein komplettes Objekt sehen. Wenn du den Adapter auf Zeug stellst, kannst du zu jedem Beginn eines Zyklus die komplette Nachricht vom go-e Adapter sehen.

**Comment by MK-2001** [comment]
Ich setze hier auf invalide, da es ein sehr spezifisches Geräte Problem ist und kein Allgemeines. Sollte ich falsch Ligen, kann das Lebel wieder entfernt werden....

**Comment by Jey-Cee** [comment]
Hab das selbe Problem, Ziemlich Nervig.
Adapter Version 1.0.18
go-e Hardware Version V3
Firmware 051.4

Hier mal Debug Log:
`
go-e.0 | 2022-01-28 09:34:56.899 | info | {"version":"B","tme":"2503-301738","rbc":"19","rbt":"7231090254","car":"1","amx":"0","amp":"16","err":"0","ast":"1","alw":"0","stp":"0","cbl":"0","pha":"56","fsp":"0","tma":[5.75,10],"dws":"6347107","dwo":"180","adi":"1","uby":"0","eto":"4306","wst":"3","fwv":"051.4","nrg":[233,232,232,0,0,0,0,0,0,0,0,0,0,0,0,0],"sse":"062812","wss":"Nicht_der_Laden","wke":"********","wen":"1","cdi":"1","tof":"101","tds":"1","lbr":"255","aho":"0","afi":"6","azo":"0","ama":"16","al1":"6","al2":"10","al3":"12","al4":"14","al5":"16","cid":"255","cch":"65535","cfi":"65280","lse":"1","ust":"0","wak":"********","r1x":"2","dto":"0","nmo":"0","sch":"AAAAAAAAAAAAAAAA","sdp":"0","eca":"0","ecr":"4004","ecd":"0","ec4":"0","ec5":"0","ec6":"0","ec7":"0","ec8":"0","ec9":"0","ec1":"0","rca":"1","rcr":"1","rcd":"","rc4":"","rc5":"","rc6":"","rc7":"","rc8":"","rc9":"","rc1":"","rna":"Frei","rnm":"EnBw","rne":"User 3","rn4":"User 4","rn5":"User 5","rn6":"User 6","rn7":"User 7","rn8":"User 8","rn9":"User 9","rn1":"User 10","loe":0,"lot":32,"lom":6,"lop":50,"log":"","lof":0,"loa":0,"lch":7225064}
-- | -- | -- | --
go-e.0 | 2022-01-28 09:34:56.899 | error | API response validation error: [{"message":"\"tme\" with value \"2503-301738\" fails to match the required pattern: /^[0-9]{10}$/","path":["tme"],"type":"string.pattern.base","context":{"regex":{},"value":"2503-301738","label":"tme","key":"tme"}}]
go-e.0 | 2022-01-28 09:34:56.874 | debug | {"version":"B","tme":"2503-301738","rbc":"19","rbt":"7231090254","car":"1","amx":"0","amp":"16","err":"0","ast":"1","alw":"0","stp":"0","cbl":"0","pha":"56","fsp":"0","tma":[5.75,10],"dws":"6347107","dwo":"180","adi":"1","uby":"0","eto":"4306","wst":"3","fwv":"051.4","nrg":[233,232,232,0,0,0,0,0,0,0,0,0,0,0,0,0],"sse":"062812","wss":"Nicht_der_Laden","wke":"********","wen":"1","cdi":"1","tof":"101","tds":"1","lbr":"255","aho":"0","afi":"6","azo":"0","ama":"16","al1":"6","al2":"10","al3":"12","al4":"14","al5":"16","cid":"255","cch":"65535","cfi":"65280","lse":"1","ust":"0","wak":"********","r1x":"2","dto":"0","nmo":"0","sch":"AAAAAAAAAAAAAAAA","sdp":"0","eca":"0","ecr":"4004","ecd":"0","ec4":"0","ec5":"0","ec6":"0","ec7":"0","ec8":"0","ec9":"0","ec1":"0","rca":"1","rcr":"1","rcd":"","rc4":"","rc5":"","rc6":"","rc7":"","rc8":"","rc9":"","rc1":"","rna":"Frei","rnm":"EnBw","rne":"User 3","rn4":"User 4","rn5":"User 5","rn6":"User 6","rn7":"User 7","rn8":"User 8","rn9":"User 9","rn1":"User 10","loe":0,"lot":32,"lom":6,"lop":50,"log":"","lof":0,"loa":0,"lch":7225064}
go-e.0 | 2022-01-28 09:34:56.873 | debug | Response: 200 - OK with data as object
go-e.0 | 2022-01-28 09:34:56.782 | debug | Starte Abfrage an: http://192.168.0.167/status

`

**Comment by Jey-Cee** [comment]
https://github.com/goecharger/go-eCharger-API-v1/issues/99

**Comment by MK-2001** [comment]
Hi. Leider suchen wir noch einen Programmierer mit einer V3 Hardware. Ich kann den Fehler bei meiner V2 nicht nachstellen. Macht gerne einen Pullrequest auf wenn jemand die Löung hat.

**Comment by Jey-Cee** [comment]
Ich hab gerade herausgefunden das Datum und die Uhrzeit in meiner Box falsch waren. Stand auf 1970.
Denke damit ist der Fehler geklärt.
