### ISSUE TITLE
adjustAmpLevelInWatts schreibt ampere oder amperePV?

### ISSUE THREAD

**Issue by nikmaier** [MK-2001/ioBroker.go-e#119]
Hallo,
ich wollte nur mal kurz fragen, weil in der Adapter Beschreibung bei amperePV steht:

**_This attribute is the same as Ampere but does not store the data permanent. After a restart this information is lost. Ampere is because of the EEPROM of the device only 100000 times writeable. If you use a Photovoltaic with go-e you should use this attribute insted of Ampere._**

Jetzt ist mir aufgefallen, wenn ich den Wert adjustAmpLevelInWatts ändere, dann schreibt er zuerste in die Variable ampere und dann in die Variable amperePV.
Zumindest laut Zeitstempel (hier wird der Wert ampere etwas früher geschrieben):

![2](https://user-images.githubusercontent.com/69574329/154977442-bcea37aa-4bbb-47af-8186-f28a04298136.jpg)

![3](https://user-images.githubusercontent.com/69574329/154977456-1226ad35-d404-40bc-a020-54dbc4834b2b.jpg)

Jetzt habe ich Angst das es eventuell nicht gut für die Box ist wenn sich da der Wert sehr oft ändert?

Oder ist das nur ein Anzeige "Fehler"?

**Comment by MK-2001** [comment]
Hi. Der Adapter schreibt in deinem Fall nur Max.

Die HW überführt den gesetzten Wert auch in das Attribut amp. Daher wird dieser beim nächsten Update ebenfalls aktualisiert.

Du kannst das besser einsehen, wenn du den adapter auf debug oder silly stellst...
