### ISSUE TITLE
Next Stable Release for Version 2

### ISSUE THREAD

**Issue by MK-2001** [MK-2001/ioBroker.go-e#12]
# Funktionen zur Version 2

## Schreiben zu allen beschreibbaren Edpunken ermöglichen:
- [x] await queue.add(() => this.setState("ampere",                             { val: o.amp, ack: true })); // write
- [x] await queue.add(() => this.setState("access_state",                       { val: o.ast, ack: true })); // write
- [x]        await queue.add(() => this.setState("allow_charging",                     { val: o.alw, ack: true })); // write
- [x] await queue.add(() => this.setState("stop_state",                         { val: o.stp, ack: true })); // write
- [ ]         await queue.add(() => this.setState("wifi.ssid",                          { val: o.wss, ack: true })); // write
- [ ]         await queue.add(() => this.setState("wifi.key",                           { val: o.wke, ack: true })); // write
- [ ]         await queue.add(() => this.setState("wifi.enabled",                       { val: o.wen, ack: true })); // write
- [ ]         await queue.add(() => this.setState("cloud_disabled",                     { val: o.cdi, ack: true }));
- [ ]         await queue.add(() => this.setState("wifi.hotspot_key",                   { val: o.wak, ack: true })); // write
- [ ]         await queue.add(() => this.setState("http_flags",                         { val: o.r1x, ack: true })); // write
- [x]         await queue.add(() => this.setState("max_load",                           { val: (o.dwo / 10), ack: true })); // write
- [ ]         await queue.add(() => this.setState("electricity_exchange.min_hours",     { val: o.aho, ack: true })); // write
- [ ]         await queue.add(() => this.setState("electricity_exchange.finish_hour",   { val: o.afi, ack: true })); // write
- [x]         await queue.add(() => this.setState("led_brightness",                     { val: o.lbr, ack: true })); // write
- [x]         await queue.add(() => this.setState("ampere_level1",                      { val: o.al1, ack: true })); // write
- [x]         await queue.add(() => this.setState("ampere_level2",                      { val: o.al2, ack: true })); // write
- [x]         await queue.add(() => this.setState("ampere_level3",                      { val: o.al3, ack: true })); // write
- [x]         await queue.add(() => this.setState("ampere_level4",                      { val: o.al4, ack: true })); // write
- [x]         await queue.add(() => this.setState("ampere_level5",                      { val: o.al5, ack: true })); // write
- [x]         await queue.add(() => this.setState("color.idle",                         { val: "#" + ("000000" + parseInt(o.cid).toString(16)).slice(6), ack: true })); // write
- [x]         await queue.add(() => this.setState("color.charging",                     { val: "#" + ("000000" + parseInt(o.cch).toString(16)).slice(6), ack: true })); // write
- [x]         await queue.add(() => this.setState("color.finish",                       { val: "#" + ("000000" + parseInt(o.cfi).toString(16)).slice(6), ack: true })); // write
- [ ]         await queue.add(() => this.setState("time_offset",                        { val: o.tof, ack: true})); // write
- [ ]         await queue.add(() => this.setState("time_daylight_saving",               { val: o.tds, ack: true })); // write
        // RFID Name 
- [ ]         await queue.add(() => this.setState("rfid.badges.1.name",                 { val: o.rna, ack: true })); // write
- [ ]         await queue.add(() => this.setState("rfid.badges.2.name",                 { val: o.rnr, ack: true })); // write
- [ ]         await queue.add(() => this.setState("rfid.badges.3.name",                 { val: o.rnd, ack: true })); // write
- [ ]         await queue.add(() => this.setState("rfid.badges.4.name",                 { val: o.rn4, ack: true })); // write
- [ ]         await queue.add(() => this.setState("rfid.badges.5.name",                 { val: o.rn5, ack: true })); // write
- [ ]         await queue.add(() => this.setState("rfid.badges.6.name",                 { val: o.rn6, ack: true })); // write
- [ ]         await queue.add(() => this.setState("rfid.badges.7.name",                 { val: o.rn7, ack: true })); // write
- [ ]         await queue.add(() => this.setState("rfid.badges.8.name",                 { val: o.rn8, ack: true })); // write
- [ ]         await queue.add(() => this.setState("rfid.badges.9.name",                 { val: o.rn9, ack: true })); // write
- [ ]         await queue.add(() => this.setState("rfid.badges.10.name",                { val: o.rn1, ack: true })); // write
- [x]         await queue.add(() => this.setState("led_save_energy",                    { val: o.lse, ack: true })); // write
- [x]         await queue.add(() => this.setState("unlock_state",                       { val: o.ust, ack: true })); // write
- [ ]         await queue.add(() => this.setState("electricity_exchange.balance_time",  { val: o.dto, ack: true })); // write
- [ ]         await queue.add(() => this.setState("energy.norway_mode",                 { val: o.nmo, ack: true })); // write

**Comment by oneill2612** [comment]
Habe mir den Adapter auch mal runtergeladen und es wird auch einiges in Opjekten angezeigt vielen dank dafür :)

Da ich nur mit 16A Laden kann (Ford KUGA) und ich eine PV Anlage auffen Dach habe die ich auch schon auslese (SENEC) gibt es eine Möglichkeit nur mit PV Überschuss zuladen ?

**Comment by MK-2001** [comment]
> Habe mir den Adapter auch mal runtergeladen und es wird auch einiges in Opjekten angezeigt vielen dank dafür :)
> 
> Da ich nur mit 16A Laden kann (Ford KUGA) und ich eine PV Anlage auffen Dach habe die ich auch schon auslese (SENEC) gibt es eine Möglichkeit nur mit PV Überschuss zuladen ?
> 
> Ich muss sagen ich bin auch erst ganz neu im Thema ioBroker :)

Schau mal hier in die Dokumentation, welche Funktion für deine PV Anlage relevant ist: docs/Readme.md

**Comment by ND42** [comment]
Hi,
ich habe mir den Adapter heruntergeladen und  in einem Docker Container installiert. Leider bekomme ich im Log folgenden Fehler:

go-e.0 | 2020-09-13 10:34:39.830 | error | (994) connect ECONNREFUSED 127.0.0.1:80
-- | -- | -- | --
go-e.0 | 2020-09-13 10:33:39.707 | info | (994) Intervall: 60
go-e.0 | 2020-09-13 10:33:39.706 | info | (994) Server: http://192.168.0.161
go-e.0 | 2020-09-13 10:33:39.682 | info | (994) starting. Version 0.1.2 in /opt/iobroker/node_modules/iobroker.go-e, node: v12.18.3, js-controller: 3.1.6

Der manuelle Zugriff über "http://192.168.0.161/status" funktioniert und gibt Werte zurück. Hab ich was übersehen oder liegt es an dem Docker Konstrukt, da der Adapter scheinbar versucht auf "127.0.0.1:80" zuzugreifen ? 
Bin für jede Hilfe dankbar...

**Comment by MK-2001** [comment]
> Hi,
> ich habe mir den Adapter heruntergeladen und in einem Docker Container installiert. Leider bekomme ich im Log folgenden Fehler:
> 
> go-e.0	2020-09-13 10:34:39.830	error	(994) connect ECONNREFUSED 127.0.0.1:80
> go-e.0	2020-09-13 10:33:39.707	info	(994) Intervall: 60
> go-e.0	2020-09-13 10:33:39.706	info	(994) Server: http://192.168.0.161
> go-e.0	2020-09-13 10:33:39.682	info	(994) starting. Version 0.1.2 in /opt/iobroker/node_modules/iobroker.go-e, node: v12.18.3, js-controller: 3.1.6
> Der manuelle Zugriff über "http://192.168.0.161/status" funktioniert und gibt Werte zurück. Hab ich was übersehen oder liegt es an dem Docker Konstrukt, da der Adapter scheinbar versucht auf "127.0.0.1:80" zuzugreifen ?
> Bin für jede Hilfe dankbar...

Hi. Ich habe dir ein neues issue dafür aufgemacht und auch gleich mal geantwortet. Kannst du es prüfen?
Gruß

**Comment by MK-2001** [comment]
Adapter is now able to handle all elements with version 1.0.41
