### ISSUE TITLE
Work with ack true/false in foreign adapters

### ISSUE THREAD

**Issue by MK-2001** [MK-2001/ioBroker.go-e#125]
Btw. ich habe gerade im code geschaut... Wenn das Attribute als ack = true ankommt, dann wird es nicht verarbeitet, da der Adapter denkt, dass dieses bereits verarbeitet wurde. 

Nun kann man darüber diskutieren, ob das auch für fremde Attribute gelten darf, oder nicht... Dennoch damit der Adapter in der Version 1.0.21 funktioniert muss es auf ack = false stehen.

_Originally posted by @MK-2001 in https://github.com/MK-2001/ioBroker.go-e/discussions/124#discussioncomment-2279962_

**Comment by nikmaier** [comment]
Hallo,
ich hätte noch eine Frage zu der Option mit "Ack?":
Bie mir werden die Objekte von "ObjektID für die aktuell verfügbare Solarleistung in Watt [W]" und "ObjektID für den aktuellen Stromverbrauch zu Hause in Watt [W]" gleichzeitig aktualisiert.
Wenn ich "Ack?" bei beiden Objekten deaktiviere, kommt die Fehlermeldung im Log: "MaxWatts ignored. You are sending to fast! Update interval in settings is currently set to: 30", obwohl beide Objekte nur alle 60 Sekunden aktualisieren, aber eben gleichzeitig.
Wenn ich jetzt bei "ObjektID für die aktuell verfügbare Solarleistung in Watt [W]" die Option "Ack?" aktiviere und bei "ObjektID für den aktuellen Stromverbrauch zu Hause in Watt [W]" deaktiviert lasse, dann kommt keine Fehlermeldung mehr.
Aber funktioniert die PV Steuerung dann noch?
(Ich kann es leider nicht testen, da ich momentan keinen Überschuss habe).

Eigentlich geht es mir nur um eine Option die PV-Steuerung kurzzeitig auszuschalten, ein Switch untern den Adapter Objekten wäre klasse. 
So bastel ich mir halt mit Blockly was, das geht auch.
