### ISSUE TITLE
ioBroker Adapter - go-eCharger Wallbox integration - Datenauslesen personalisieren (nicht alle Daten auslesen)

### ISSUE THREAD

**Issue by Strobi-Boy** [MK-2001/ioBroker.go-e#134]
Gibt es irgendwie eine Möglichkeit, beim ioBroker Adapter "go-eCharger Wallbox integration" nur einzelne Messwerte auslesen zu lassen?
Wenn man mehrere go-eCharger hat und diese regelmäßig ausliest, verbraucht das doch ganz schön Prozessorleistung.
Ich würde gerne nur die für mich wichtigen Daten (z.B. Ladeleistung, RFID, Kabel gesteckt, etc.) auslesen - den Rest brauche nicht nicht...

Viele Grüße

**Comment by MK-2001** [comment]
Hi. Status quo nicht. 
Die API (v1) gibt auch nur alle Informationen auf einmal zurück. Bei der V2 ist das möglich. Derzeit liegt mir aber die HW noch nicht vor. Daher kann ich dagegen leider nicht programmieren.

**Comment by Strobi-Boy** [comment]
Ist es möglich, das Aktualisierungsintervall "on the fly" z.B. via Datenpunkt zu ändern?
Z.B. würde ich gerne während eines aktiven Ladevorgangs die Aktualisierung auf 5s stellen. Wenn die Wallbox im Standby-Betrieb ist, würde ich hingegen die Daten nur alle 30s abrufen... Da ist's ja dann nicht so spannend...
