### ISSUE TITLE
Feature: PV Überschuss - Ladevorgang stoppen bei zu wenig Überschuss

### ISSUE THREAD

**Issue by nikmaier** [MK-2001/ioBroker.go-e#138]
Hallo,
erstmal vielen Dank für den wirklich sehr tollen Adapter.
Ich finde auch das interne Script zum Überschussladen super, da spart man sich einiges an Scripten.
Was noch wirklich sehr gut wäre, eine Möglichkeit, dass der Ladevorgang komplett stoppt wenn nicht genug Überschuss vorhanden ist.
Weil momentan ist es ja so, dass bei zu wenig Überschuss die Ladung auf 6A geht, aber nicht stoppt.

Vielleicht kann man das ja relativ leicht einbauen, würde bestimmt einigen gefallen 👍

**Comment by mbr-sn** [comment]
Das geht nicht so leicht, weil die Go-e Hardware da eine Einschränkung hat. Man könnte das theoretisch über den "alw" Parameter steuern, der wird aber ins EEPROM geschrieben und das darf nicht zu oft passieren.
Siehe diese Diskussion hier: https://github.com/goecharger/go-eCharger-API-v1/issues/27
