### ISSUE TITLE
ioBroker - Temp6 has no existing object

### ISSUE THREAD

**Issue by Enno-von-Schwerin** [MK-2001/ioBroker.go-e#141]
Adapter 1.0.18 (neueste Version in ioBroker Repo wirft aktuell den folgenden Fehler:

State "go-e.0.temperatures.tempereature6" has no existing object, this might lead to an error in future versions

**Comment by MK-2001** [comment]
Please update to Version 1.0.23 or higher. 
This will fix this issue.
