### ISSUE TITLE
Cannot read propeety 'finish' of undefined at GoE.adjustAmpLevelInWatts

### ISSUE THREAD

**Issue by Schbatzafresser** [MK-2001/ioBroker.go-e#143]
**Describe the bug**  
Adapter crashes and has to be restarted

**To Reproduce**  
pops up once in a while, for unknown reason. No other problems so far. 

**Expected behavior**  

**Screenshots & Logfiles**  
instance system.adapter.go-e.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
go-e.0 | 2022-06-13 12:45:30.451 | error | TypeError: Cannot read property 'finish' of undefined at GoE.adjustAmpLevelInWatts (/opt/iobroker/node_modules/iobroker.go-e/main.js:793:25)
go-e.0 | 2022-06-13 12:45:30.450 | error | unhandled promise rejection: Cannot read property 'finish' of undefined
go-e.0 | 2022-06-13 12:45:30.448 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Versions:**  
 - Adapter version: 1.0.23
 - JS-Controller version: 5.7.0 
 - Node version: <node-version> 
 - Operating system: 

**Additional context**

**Comment by nikmaier** [comment]
Hallo,
habe genau das selbe, seit dem Update von 1.0.18 auf die neue 1.0.23.
Sobald ich den AMX Wert ändere kommen diese Fehlermeldungen im Log.

Gibt es hier schon eine Lösung?

**Comment by MK-2001** [comment]
Danke für die Meldung. Ich denke es ist nun in der Version 1.0.25 behoben. Derzeit noch auf Beta.
