### ISSUE TITLE
Bei einphasigem Anschluss werden WATTs auf Phase1 und Phase3 angezeigt

### ISSUE THREAD

**Issue by heckmic** [MK-2001/ioBroker.go-e#144]
Bei einphasigem Anschluss werden WATTs auf Phase1 und Phase3 angezeigt

![image](https://user-images.githubusercontent.com/58993863/175015546-8f637964-58ca-42da-9320-ab39b42e184e.png)

**Comment by MK-2001** [comment]
Close because stale.
