### ISSUE TITLE
The script charges with too many amps (up to 32)

### ISSUE THREAD

**Issue by FalkeSR** [MK-2001/ioBroker.go-e#145]
Hello, I would like to load a one phase car with the script. In debug mode I see that he would like to charge with e.g. 2400 watts. Then he sets an ampere value in the Go-E Charger App 18 amps. I also had 23 amps. What can be the reason? Thanks for the help!

**Comment by MK-2001** [comment]
Hi,

Could you please provide the los in debug mode? Thanks in advance.

**Comment by MK-2001** [comment]
Close because stale.
