### ISSUE TITLE
MaxWatts ignored. You are sending to fast!

### ISSUE THREAD

**Issue by bierhurra** [MK-2001/ioBroker.go-e#149]
Ich habe nun alle Dokumentationen durchforstet aber leider nicht gefunden was die Warnmeldung behebt.
Ich habe bei der Variable MaxWatts 11000 eingetragen. 
Ich habe mit den Einstellungen für "Aktualisierungsinterval" und "max. Intervall zum Schreiben" experimentiert. Leider ohne Erfolg.
Das Aktualisierungsintervall wird laut Anleitung mit 5s empfohlen, da es keine Cloudabfragen sind.
Geschrieben werden soll nicht öfter als 30s. Ich habe nun 120 eingestellt. trotzdem kommt im 60s Takt die Warnmeldung "MaxWatts ignored. You are sending to fast! Update interval in settings is currently set to: 120".
Die Meldung erscheint im Log aktuell 3 mal mit ein paar Millisekunden abstand.
Könnte es sein, das tatsächlich 3 mal hintereinander versucht wird den Wert zu setzen?

go-e.0 | 16201 | 2022-10-01 18:05:30.055 | warn | MaxWatts ignored. You are sending to fast! Update interval in settings is currently set to: 120
-- | -- | -- | -- | --
go-e.0 | 16201 | 2022-10-01 18:05:30.053 | warn | MaxWatts ignored. You are sending to fast! Update interval in settings is currently set to: 120
go-e.0 | 16201 | 2022-10-01 18:05:30.001 | warn | MaxWatts ignored. You are sending to fast! Update interval in settings is currently set to: 120

Danke im Voraus?

**Comment by MK-2001** [comment]
Derzeit ist
