### ISSUE TITLE
PV Steuerung kurzzeitig deaktivieren?

### ISSUE THREAD

**Issue by nikmaier** [MK-2001/ioBroker.go-e#153]
Hallo,
die PV Steuerung mit Überschuss laden funktioniert perfekt, aber gibt es irgendeine Möglichkeit, dass man dies kurzzeitig abschalten kann?
Irgendein Objekt wäre hier super, das man auf true oder false setzen kann?
Weil ab und zu, gerade im Winter muss man doch mal schnell laden mit 16A und wenn die PV Objekte im Adapter eingetragen sind, dann stellt sich natürlich die Wallbox immer auf 6A.

**Comment by goerdy** [comment]
Hi,
ich hänge mich hier mal ran.
Ich habe bisher die komplette Überschussladung per script realisiert. Jetzt bin ich auf die im Adapter eingebaute Überschussladung umgestiegen. Ich brauche aber weiterhin eine Option um auch manuell laden zu können. Die Sonne scheint ja nicht immer.
Wäre super wenn das implementiert werden würde. Oder gibt es da schon eine möglichkeit die ich übersehen habe?
Vielen Dank und beste Grüße

**Comment by nikmaier** [comment]
@guerdy
Ich mache das mit einer Variable, im Adapter übergebe ich die Werte mit einer Variable:

![1](https://user-images.githubusercontent.com/69574329/227164586-02425273-17c5-4af6-9619-8f06c7130cef.JPG)

 dann habe ich ein Blockly wo ich z.B. "Wallbox_aus" auf true setze, dann werden keine Daten mehr für den Adapter aktualisiert und somit ist die PV Steuerung aus:

![2](https://user-images.githubusercontent.com/69574329/227164834-50a68ff5-418c-4828-8a30-0da3cc671c36.JPG)

**Comment by MK-2001** [comment]
Wird eingebaut. 
Bald kommt ein größeres Update...

**Comment by nikmaier** [comment]
@MK-2001 
Sehr cool! Das ist ja ein richtiges Ostergeschenk. TOP!
Danke. :-)
