### ISSUE TITLE
no existing object - in aktueller Version 

### ISSUE THREAD

**Issue by fuchs-1978** [MK-2001/ioBroker.go-e#158]
Version der Adapter 
1.0.26

Hardwarerevision 2

Ich bekomme folgende Warnung:

State "go-e.2.temperatures.maintemperature" has no existing object, this might lead to an error in future versions

Hier ist bei mir das Objekt anders geschrieben

**Comment by dft601** [comment]
ja, stimmt, hab ich auch festgestellt.... Da ist ein Rechtschreibfehler im Objekt.
das steht 
go-e.0.temperatures.maintemper**e**ature
statt
go-e.0.temperatures.maintemperature
