### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by MK-2001** [MK-2001/ioBroker.go-e#16]
Hi,
ich habe mir den Adapter heruntergeladen und  in einem Docker Container installiert. Leider bekomme ich im Log folgenden Fehler:

go-e.0 | 2020-09-13 10:34:39.830 | error | (994) connect ECONNREFUSED 127.0.0.1:80
-- | -- | -- | --
go-e.0 | 2020-09-13 10:33:39.707 | info | (994) Intervall: 60
go-e.0 | 2020-09-13 10:33:39.706 | info | (994) Server: http://192.168.0.161
go-e.0 | 2020-09-13 10:33:39.682 | info | (994) starting. Version 0.1.2 in /opt/iobroker/node_modules/iobroker.go-e, node: v12.18.3, js-controller: 3.1.6

Der manuelle Zugriff über "http://192.168.0.161/status" funktioniert und gibt Werte zurück. Hab ich was übersehen oder liegt es an dem Docker Konstrukt, da der Adapter scheinbar versucht auf "127.0.0.1:80" zuzugreifen ? 
Bin für jede Hilfe dankbar...

_Originally posted by @ND42 in https://github.com/MK-2001/ioBroker.go-e/issues/12#issuecomment-691636864_

**Comment by MK-2001** [comment]
@ND42

Hi, lass mal bitt in den Settings das http:// weg. Also statt "http://192.168.0.161" nur "192.168.0.161".
Ich werde es in der Beschreibung in der nächsten Version verbessern. 

Wäre super, wenn du mir auch schreibst, ob es funktioniert hat.

**Comment by ND42** [comment]
Hat leider nicht geholfen:

go-e.0 | 2020-09-14 12:30:14.284 | error | (1009) connect ECONNREFUSED 127.0.0.1:80
-- | -- | -- | --
go-e.0 | 2020-09-14 12:29:14.466 | error | (1009) connect ECONNREFUSED 127.0.0.1:80
go-e.0 | 2020-09-14 12:28:14.278 | info | (1009) Intervall: 60
go-e.0 | 2020-09-14 12:28:14.277 | info | (1009) Server: 192.168.0.161
go-e.0 | 2020-09-14 12:28:14.172 | info | (1009) starting. Version 0.1.2 in /opt/iobroker/node_modules/iobroker.go-e, node: v12.18.3, js-controller: 3.1.6
host.iobroker | 2020-09-14 12:28:09.083 | info | instance system.adapter.go-e.0 started with pid 1009
host.iobroker | 2020-09-14 12:28:08.892 | info | "system.adapter.go-e.0" enabled

**Comment by MK-2001** [comment]
für mich ist derzeit noch nicht klar, warum er 127.0.0.1 (localhost) versuchen will zu erreichen, obwohl er eine IP Adresse genannt bekommt. Ist aus dem laufenden Docker Container der 192.x.x.x host zu erreichen? 
```
docker exec -it myContainer /bin/bash   
ping 192.x.x.x
```

**Comment by ND42** [comment]
Die IP kann von dem Docker host nicht aufgelöst werden:
root@iobroker:/opt/iobroker# host 192.168.0.161
**Host 161.0.168.192.in-addr.arpa. not found: 3(NXDOMAIN)**
root@iobroker:/opt/iobroker# ping 192.168.0.161
PING 192.168.0.161 (192.168.0.161) 56(84) bytes of data.
64 bytes from 192.168.0.161: icmp_seq=1 ttl=254 time=21.5 ms
64 bytes from 192.168.0.161: icmp_seq=2 ttl=254 time=16.8 ms

Wobei die Anbindung des Solarlog Moduls trotzdem funktioniert, obwohl dessen IP auch nicht aufgelöst werden kann...

**Comment by ND42** [comment]
Danke, funktioniert jetzt :-)
