### ISSUE TITLE
SolarLoadOnly Erklärung

### ISSUE THREAD

**Issue by nikmaier** [MK-2001/ioBroker.go-e#160]
Hallo,
erstmal vielen Dank für den schon besprochenen Punkt "SolarLoadOnly".

Kannst du uns bitte mal aufklären, wie der genau funktioniert?

Ich habe jetzt z.B. mit 11A gerade geladen.
Dann habe ich den Punkt "SolarLoadOnly" auf true gesetzt, dann hat sich die Wallbox ausgeschaltet und nicht mehr eingeschaltet.

Kannst du kurz die Logik die du eingebaut hast erklären?

Auch der Punkt "Negate" ist neu in der Adapter Config, konnte hier auch noch nicht rausfinden für was das ist?

Danke im Voraus.

P.S. Habe jetzt gerade getestet, bei mir funktioniert seit dem Update überhaupt keine Überschussladung mehr, bleibt immer auf der gleichen Ampere Zahl, egal ob SolarLoadOnly auf false oder auf true.

**Comment by nikmaier** [comment]
Hallo,
habe nun einiges getestet, musste jetzt wieder downgrade machen, da hier leider einiges nicht mehr so gut funktioniert wie vorher.

Ich liste das ganze mal auf, vielleicht ist es auch nur eine Einstellungssache die ich im neuen Adapter nicht kappiere:

1. Das "Negate" ist super, so kann man Werte die Negative angezeigt werden in Positiv umwandeln oder? Leider besteht die Möglichkeit nicht bei "ObjektID für den aktuellen Stromverbrauch zu Hause in Watt [W]", hier wäre auch Negate super, da Fronius diesen Wert (P_Load) auch negativ anzeigt.
(Das nur nebenbei, ist für mich nicht so wichtig)

2. Wenn ich "SolarLoadOnly" auf true habe: Bei Änderungen des Wertes "ObjektID für den aktuellen Stromverbrauch zu Hause in Watt [W]" ändert sich die Ampere Zahl nicht mit.
(Auch nur nebenbei, ist für mich auch nicht so wichtig)

3. Jetzt kommen wir zum eigentlichen Hauptproblem:
Wenn "SolarLoadOnly" auf true ist und der PV Wert unter den aktuellen Stromverbrauch fällt, dann schaltet die Box jetzt aus und geht nicht mehr wie vorher auf 6A.
Das ist für den ein oderen anderen der jetzt eine "reine" PV-Überschuss Steuerung hat bestimmt ein absolut mega super Update Punkt.
Aber für mich leider ein absolutes Chaos, ich will/muss den Stop selber einstellen können, da ich ab 50% Batterie und Überschuss das Überschuss-Laden anfangen will und bei 90% Batterie und keinen Überschuss abschalten will, aber nicht wenn morgen Feiertag ist usw.
Lange Rede, kurzer Sinn.
Fakt ist, ich kann nicht mehr den Adapter so nutzen wie vorher oder übersehe ich da was?

Gibt es eine Möglichkeit noch einen weiteres Objekt einzubauen mit "Wallbox abschalten mit PV Steuerung" true/false oder so.
Ich denke es geht auch ganz schön auf die EEPROM der Wallbox wenn es bei einem wolkigem Tag immer ein und ausschaltet.

Wäre super wenn du hier nochmal "nachjustieren" könntest :-)

Danke im Voraus.

**Comment by MK-2001** [comment]
Hallo,

Ich muss mir nochmals deine Kommentare in den kommenden Tagen in Ruhe durchlesen. Ich habe auch Fronius im Einsatz. Meine Konfiguration habe ich der Doku notiert: https://github.com/MK-2001/ioBroker.go-e/blob/main/docs/Readme.md#functionalities

**Comment by nikmaier** [comment]
Also ich hab nicht die Git-Version installiert, sondern die 1.0.27 von stable repro.
Habe deine Anleitung gelesen, aber hier werd ich teilweise nicht schlau:

![image](https://user-images.githubusercontent.com/69574329/230783342-c0452e2e-752e-43fb-97bb-84b598032173.png)

Punkt solarPower: Das soll wahrscheinlich im Adapter der Punkt "ObjektID für die aktuell verfügbare Solarleistung in Watt [W]" sein. Hier gibst du den Netzbezug an, also fronius.0.powerflow.P_Grid, für mich ist das aber fronius.0.powerflow.P_PV.
Punkt houseConsuption: Das soll wahrscheinlich im Adapter der Punkt "ObjektID für den aktuellen Stromverbrauch zu Hause in Watt [W]" sein. Hier schreibst du das Fronius den nicht hat, für mich ist das der Wert von fronius.0.powerflow.P_Load.
Zweiter Punkt houseConsuption soll wahrscheinlich der Akku sein.

Lies dir irgendwann mal die Punkte oben durch.
Eilt ja nicht, die Version 1.0.25 läuft ja perfekt.

**Es geht eigentlich auf den Punkt gebracht nur um eines: Es sollte bei der neuen Version einfach weiterhin (oder zusätzlich) die Möglichkeit bestehen das die Wallbox NICHT ausschaltet, sondern nur auf 6A runterregelt. Einfach so wie die Version 1.0.25 es auch jetzt macht :-)**

Danke im Voraus.
