### ISSUE TITLE
Phasenumschaltung (psm) nicht möglich?

### ISSUE THREAD

**Issue by Omega236** [MK-2001/ioBroker.go-e#162]
scheinbar kann man die Phasen nicht über den Adapter umschalten bzw den Status sehen.

wäre echt sucher wenn der Datenpunkt psm übernommen wird.

**Comment by MK-2001** [comment]
Sehen geht.
Die API v2 befindet sich noch in der Entwicklung. Wahrscheinlich Sommer, wenn er denn mal kommt...

**Comment by Omega236** [comment]
Welcher Datenpunktist das (zum sehen)?

**Comment by MK-2001** [comment]
Das sind die Datenpunkte

go-e.0.energy.phase1.postContactorActive

Entsprechend für alle drei Phasen. 
Es gibt noch einen kombinierten. Der muss nach octet ausgewertet werden.
