### ISSUE TITLE
Adapter crashes

### ISSUE THREAD

**Issue by Horgul123** [MK-2001/ioBroker.go-e#163]
EDIT: With APIv1 it works, switching to v2 as explained in the adapter the following happens (No sure if your "use API v1" is still valid)

------------
I got a new go-e Gemini 11kW Hardware Version V4
When I start the adapter it crashes.

Debug says:
`<html>
<body>

go-e.0 | 2023-05-25 18:33:43.381 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
go-e.0 | 2023-05-25 18:33:43.380 | info | terminating
go-e.0 | 2023-05-25 18:33:43.360 | error | this.translationObjectV2.keys is not a function
go-e.0 | 2023-05-25 18:33:43.360 | error | TypeError: this.translationObjectV2.keys is not a function at GoE.getStateFromDevice (/opt/iobroker/node_modules/iobroker.go-e/main.js:331:76) at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:126:20) at GoE.emit (node:events:513:28) at GoE.emit (node:domain:489:12) at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8232:26
go-e.0 | 2023-05-25 18:33:43.358 | error | unhandled promise rejection: this.translationObjectV2.keys is not a function
go-e.0 | 2023-05-25 18:33:43.358 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
go-e.0 | 2023-05-25 18:33:43.356 | debug | Subscribe foreign object 0_userdata.0.PV_Produktion
go-e.0 | 2023-05-25 18:33:43.355 | debug | Subscribe foreign object 0_userdata.0.PV_Eigenverbrauch
go-e.0 | 2023-05-25 18:33:43.347 | warn | Sentry enabled. You can switch it off in settings of the adapter.
go-e.0 | 2023-05-25 18:33:43.346 | info | Intervall: 60
go-e.0 | 2023-05-25 18:33:43.346 | info | Server: go-eCharger.fritz.box
go-e.0 | 2023-05-25 18:33:43.345 | info | Update selectable values from ["alw","car","amp"] to alw,rbc,rbt,car,amp
go-e.0 | 2023-05-25 18:33:43.325 | info | starting. Version 1.0.27 in /opt/iobroker/node_modules/iobroker.go-e, node: v18.15.0, js-controller: 4.0.24

</body>
</html>`

1.0.27 in /opt/iobroker/node_modules/iobroker.go-e, node: v18.15.0, js-controller: 4.0.24

**Versions:**  
 - Adapter version: 1.0.27
 - JS-Controller version: 4.0.24
 - Node version: v.18.15.0
 - Operating system: debian

**Comment by MK-2001** [comment]
Thank you for your info.
Please use API V1 only. V2 is not ready yet on all environments
