### ISSUE TITLE
Überschussladung funktioniert nicht mehr seit Version 1.0.27

### ISSUE THREAD

**Issue by nikmaier** [MK-2001/ioBroker.go-e#164]
Hallo,
ich wollte jetzt nochmal nachfragen weil ich den Hauptthreat im Iobroker Forum so gut es mir möglich ist supporte.
Habe jetzt auch mal eine Anleitung geschrieben (kann auch gerne etwas daraus fürs Wiki entnommen werden), weil immer sehr viele fragen wie die Überschuss-Regelung funktioniert:

https://forum.iobroker.net/post/997951

Allerdings gibts ständig Rückmeldung das es bei der neuen 1.0.27 nicht mehr funktioniert.

Deswegen wollte ich (um auch anderen zu helfen) wissen, was genau jetzt bei der 1.0.27 anders ist bzw. warum es nicht mehr funktioniert.

Und dann bräuchte ich noch eine Erklärung der folgenden Punkte:
- Punkt "SolarLoadOnly". Wenn dieser auf True ist sollte doch nur per Überschuss geladen werden
- Wann wird die Box mit ausgeschaltet und wann nicht, ist es überhaupt noch möglich weiterhin (wie bei Version 1.0.25) ohne Box Ausschaltung die Überschuss Ladung zu nutzen?
- Der Punkt "Negate" im Adapter. Soll dieser eine Negative Zahl in eine Positive wandeln?

Falls du Logs benötigst oder ich was testen soll/kann bitte Bescheid geben.

Danke im Voraus.

**Comment by MK-2001** [comment]
Hi.

In allen drei Punkten bist du richtig. 
Ja, Logs wären mal gut auch im Debug Modus.

**Comment by nikmaier** [comment]
Danke für deine schnelle Rückinfo.
Ok dann werde ich das testen und die Logs zur Verfügung stellen.
Aber eines müsste ich noch zum Test wissen:

Wann schaltet die Box ab bzw. wo stellt man ein ob die Überschussladung mit Boxabschaltung erfolgen soll oder ohne?

**Comment by MK-2001** [comment]
Wenn nicht genügend Strom zur Verfügung steht, würde bei SolarOnly die Box immer abschalten.

Ich müsste einen zweiten Schalter einfügen als LoadWith6AAtLeast

Wenn du mir dazu noch erklären könntest warum das benötigt wird, damit ich den Bedarf auch verstehe...

Meine pers. Einstellung ist entweder nur Solar, oder vom Netz aber dann kann man auch volle Last fahren.

**Comment by nikmaier** [comment]
Ja der Schalter wäre wirklich für viele wichtig.
Hier nur einmal ein paar Punkte:

1. Ich will nicht, dass die Box bei einem wolkenreichen Tag immer wieder an und ausschaltet, da es ja ins Eprom geschrieben wird.
2. Ich will das meine Wallbox erst ausschaltet wenn meine PV-Batterie unter 90% ist, so habe ich einen guten Puffer an wolkenreichen Tagen
3. Und das wohl allerwichtigste für alle: Wegen der PHASENUMSCHALTUNG.
   Dann wäre es ja so, dass die Box bei 3-Phasen Ladung ausschalten würde, wenn unter 6A und kein Überschuss mehr da ist, hier wollen aber viele natürlich erstmal auf 1-Phase umschalten und dann weiter laden.
Weil Phasenumschaltung ist ja nicht bei der neuen Version implementiert oder?

Wäre schon super wenn es den Schalter gibt.

Werde dann am Wochenende mal einige Tests machen.

**Comment by MK-2001** [comment]
Also 1 ist ein Irrglaube, welche er nur auf amp und Amy zutrifft. Alw wird nichts ins eprom geschrieben. Also andauern On-/ Off macht gar nichts.

3. ist noch nicht implementiert.

Ist es dann trotz Irrglaube wichtig?

**Comment by nikmaier** [comment]
Echt, ok, das wusste ich nicht, danke für die Info.
Aber nichts desto trotz, solange die Phasenumschaltung noch nicht implementiert ist wäre für mich (und für einige im Forum was ich weis) echt unabdingbar.
Wäre schon echt super wenn du den Schalter implementieren kannst.

**Comment by nikmaier** [comment]
Wollte nochmal kurz nachfragen, ob du die Implementierung des Schalters machen wirst? Weil erst dann macht es für mich Sinn alles komplett durchzutesten, sonst muss ich jetzt die neue Version installieren, alles testen und dann wieder auf die alte Version zurück.

**Comment by MK-2001** [comment]
Hi,
Ich werde die Implementierung umsetzen. Wann kann ich dir nicht sagen. Ich werde mit dem Commit das issue schließen.

**Comment by mbr-sn** [comment]
> Also 1 ist ein Irrglaube, welche er nur auf amp und Amy zutrifft. Alw wird nichts ins eprom geschrieben. Also andauern On-/ Off macht gar nichts.

alw wird **nicht** ins eeprom geschrieben? Das wäre dann in der Tat ein sehr weitverbreiteter Irrglaube, siehe die Diskussionen im ioBroker-Forum.
Das könnte man dann in der Doku mal sehr ausdrücklich hervorheben (was ins EEPROM geschrieben wird und was nicht), damit wäre vielen geholfen denke ich.

**Comment by nikmaier** [comment]
Wie im Forum schon geschrieben:

@MK-2001 hat völlig Recht: **ALW schreibt NICHT ins Eeprom, aber NUR ab den V3 Wallboxen!**

Diese Aussage habe ich auch schriftlich direkt von Go-E erhalten:

```
vielen Dank für Ihre Anfrage!

Bei der Version 3 und V4 wird alw nicht in den Eprom geschrieben.

Somit kann der Charger so oft wie möglich ein und ausgeschaltet werden.
```

**Comment by nikmaier** [comment]
> Hi, Ich werde die Implementierung umsetzen. Wann kann ich dir nicht sagen. Ich werde mit dem Commit das issue schließen.

Hallo @MK-2001,
ich wollte mal nachfragen, weil das Ticket jetzt geschlossen ist, ob diese Implementierung noch geplant ist?

Danke im Voraus.

**Comment by nikmaier** [comment]
@MK-2001 
Sorry das ich dieses Ticket jetzt nochmal aufmachen muss, aber es ging ja in diesem Issue darum, dass ein weitere Button mit z.B. "LoadWith6AAtLeast" eingefügt wird.
Ich habe jetzt die Github Version installiert, leider finde ich diesen State nirgends. 
Wollte jetzt nur den aktuellen Stand wissen ob dieser State eingefügt wurde und ich nur nicht finde oder ob dieser State nicht mehr eingefügt wird?
Vielen Dank im Voraus.

**Comment by MK-2001** [comment]
@nikmaier 
bei mir sehe ich den Schalter:
<img width="763" alt="image" src="https://github.com/MK-2001/ioBroker.go-e/assets/36983163/7e4405e5-f9d0-4171-b339-5440ceaef40c">

**Comment by nikmaier** [comment]
@MK-2001 
Ich will echt nicht nerven, will nur eine Rückmeldung geben.
Geht leider immer noch nicht, auch wenn der Haken bei "laden mit min 6A" aktiviert ist schaltet die Wallbox komplett aus.

Habe auf meinem Testsystem die aktuelle Git-Version installiert und getestet.
Habe hierzu zwei Variablen erstellt für den Test:

![image](https://github.com/MK-2001/ioBroker.go-e/assets/69574329/9e63c767-f389-4ff2-b89d-50e03a7c01a9)

Hab diese im Adapter eingetragen und den Haken rein:

![image](https://github.com/MK-2001/ioBroker.go-e/assets/69574329/2fa160ae-27a8-46b6-8a01-2cc0635dd225)

SolarOnly ist auf true:

![image](https://github.com/MK-2001/ioBroker.go-e/assets/69574329/889a140c-7d3a-45c7-9297-c62562ebbf5f)


"Strom_Haus" lasse ich auf 10000 und setze "Strom_PV" auf 10500 --> Ampere gehen von 6A auf 8A --> soweit alles korrekt.

Setzte ich eine Minute danach "Strom_PV" auf 500 --> geht die Wallbox aus:

![image](https://github.com/MK-2001/ioBroker.go-e/assets/69574329/c0590708-83e9-4e99-97cb-9aa81efb7ca2)

Testweise habe ich dann eine Minute danach "Strom_PV" auf 20000 gesetzt --> amp geht hoch, aber Wallbox bleibt aus und schaltet nicht wieder ein.

----------------------------------------------

Hab dann mal testweise den Haken bei "Laden mit min 6A" im Adapter raus, solaronly auf true
--> dann geht keinerlei PV Steuerung mehr. Egal was ich dann bei "Strom_Haus" bzw. "Strom_PV" eingebe wird ignoriert.

----------------------------------------------

Wie gesagt nur eine Info, ist ja auch nicht weiter schlimm, die Version 1.0.25 läuft ja perfekt.
Vielleicht hast du ja Lust das nochmal anzuschauen.
Danke im Voraus.

**Comment by nikmaier** [comment]
Hallo,
ich wollte jetzt nur nochmal nachfragen, ob du den Bug mit "Laden mit min 6A" noch überarbeiten kannst/willst?
Weil im Forum fragen schon wieder ein paar warum das nicht geht, ich weise dann immer auf die 1.0.25 hin, aber irgendwann wird ein update wohl unausweichlich sein. 
Dann wäre natürlich super wenn das mit der neuen Version genauso gut funktioniert wie mit der alten 1.0.25.
Danke im Voraus.

**Comment by MK-2001** [comment]
Hallo.

das ist seit November implementiert und funktioniert bei mir sehr gut.

**Comment by MK-2001** [comment]
@Dax88 @nikmaier 
Derzeit scheint das Problem behoben zu sein.
Bitte sicherstellen, dass die Attribute analog der Beschreibung aus eingesetzt werden.
<img width="687" alt="image" src="https://github.com/MK-2001/ioBroker.go-e/assets/36983163/6b104ada-1102-4a79-a4c6-a633f8a36220">

Sollte es dennoch weiterhin einen Fehler geben, bitte mit der aktuellen Version das Log auf Silly mir zukommen lassen, dann kann ich mir das anschauen.

**Comment by nikmaier** [comment]
@MK-2001 
Hallo Markus,
danke dir.
Ich habe jetzt meinen Testaufbau nochmal aufgebaut und nochmal alles komplett getestet.
Die 1.0.29 habe ich anscheinend wirklich noch nicht ausprobiert.
Die PV Steuerung nach "oben" geht jetzt soweit.
**Es ist aber noch ein Bug drin:**

**Wenn z.B. 12A eingestellt sind und der PV Wert geht auf einen Schlag in den Keller dann bleibt dieser auf 12A und geht nicht auf 6A, sieht man im Log.**

Einstellungen:
Adapter so eingestellt wie oben im Post von mir
Solarony auf true
Manuell auf 12A 
Strom Haus auf Wert 5000
PV auf Wert 5000

Test:
PV Wert auf 1000 statt 5000 gestellt --> Es bleibt bei 12A, müsste aber auf 6A runterspringen.
(Wenn man in kleinen Schritten nach unten geht, dann funktioniert es, denke hier ist nur noch das Problem das bei dieser Meldung "Continue because loadWith6AAtLeast is activated" zusätzlich 6A eingestellt bzw. einprogrammiert werden müssen.
Wenn du das noch machen kannst wäre super, denke dann läuft der Adapter wieder optimal.

Hier das Log:

<html><body>


go-e.0 | 2024-01-30 10:26:05.382 | debug | Continue because loadWith6AAtLeast is activated.
-- | -- | -- | --
go-e.0 | 2024-01-30 10:26:05.381 | debug | Current  used 2387 Watts with 11 Ampere (sum) by 1 Phases and adjusting this  with  -4102 watts by 217 Volts (avg) to new max of -8 Amperes per Phase
go-e.0 | 2024-01-30 10:26:05.316 | debug | Start ajust by foreign Object with -4102 Watts
go-e.0 | 2024-01-30 10:25:34.545 | debug | Synctime: 3001241025
go-e.0 | 2024-01-30 10:25:34.524 | debug | {"version":"B","tme":"3001241025","rbc":"74","rbt":"680487","car":"2","amx":"12","amp":"12","err":"0","ast":"0","alw":"1","stp":"0","cbl":"20","pha":"57","fsp":"1","tma":[9.25,14.375],"dws":"168261","dwo":"180","adi":"1","uby":"0","eto":"26040","wst":"3","fwv":"055.8","nrg":[217,223,221,3,114,0,0,25,0,0,0,257,100,14,11,99],"sse":"077645","wss":"WLAN8","wke":"********","wen":"1","cdi":"0","tof":"101","tds":"1","lbr":"255","aho":"0","afi":"6","azo":"0","ama":"16","al1":"6","al2":"10","al3":"12","al4":"14","al5":"16","cid":"255","cch":"65535","cfi":"65280","lse":"0","ust":"0","wak":"********","r1x":"2","dto":"0","nmo":"0","sch":"AAAAAAAAAAAAAAAA","sdp":"0","eca":"0","ecr":"0","ecd":"0","ec4":"0","ec5":"0","ec6":"0","ec7":"0","ec8":"0","ec9":"0","ec1":"0","rca":"1","rcr":"","rcd":"","rc4":"","rc5":"","rc6":"","rc7":"","rc8":"","rc9":"","rc1":"","rna":"n/a","rnm":"n/a","rne":"n/a","rn4":"n/a","rn5":"n/a","rn6":"n/a","rn7":"n/a","rn8":"n/a","rn9":"n/a","rn1":"n/a","loe":1,"lot":16,"lom":6,"lop":50,"log":"ZIGWWINN","lof":8,"loa":13,"lch":38}


</body>
</html>

**Comment by nikmaier** [comment]
@MK-2001 
Hi,
ich wollte jetzt nochmal kurz nachfragen, weil das Thema gerade im Forum aufgekommen ist.
Ist dieser kleine Bug schon behoben? Siehe mein letzter Post?
Weil dann könnte ich den Leuten im Forum besser helfen :-)

**Comment by MK-2001** [comment]
Nein, noch nicht. Ich werde meinen commit hier verlinken, wen es eingebaut wird.

**Comment by Dax88** [comment]
Bei mir funktioniert die 1.0.29 immer noch nicht. Im log bekomme ich die Meldung Error in calculateFromForeignObjects: "Cannot read properties of null (reading 'ack')". Mit der 1.0.25 läuft's wie es soll.

**Comment by MK-2001** [comment]
@Dax88 diesen Fehler habe ich soeben nachstellen können. SolarLoadOnly ist eigentlich ein Boolean steht aber auf "null"

**Comment by nikmaier** [comment]
@MK-2001 
Sorry, aber der Bug in diesem Post: https://github.com/MK-2001/ioBroker.go-e/issues/164#issuecomment-1916449218 ist immer noch drin, habe es gerade versucht.
Bei einem PV Abfall der unter die 6A gehen würde, bleiben die vorhandenen Ampere einfach stehen und gehen nicht auf 6A runter und im Log kommt dann immer: "Continue because loadWith6AAtLeast is activated."
