### ISSUE TITLE
Einheit für "Stromfluss der Heimbatterie"

### ISSUE THREAD

**Issue by alexanderkartschall** [MK-2001/ioBroker.go-e#165]
Hallo,

ich benutzt die Version 1.0.27. Ich möchte gerne Überschuss laden und habe ein PV-Anlage mit Speicher. 

Ich verstehe nicht was ich unter "Objekt-ID für den aktuellen Stromfluss der Heimbatterie in Watt [W]" eintragen soll. Wenn ich eintrage was dort steht funktioniert Überschussladen nicht. Wenn ich mir die darunter angegebene Formel anschaue (houseBattery - bufferToBattery), sollten diese beiden Variablen ja eigentlich die selbe Einheit haben - houseBattery ist aber W und bufferToBattery in Wh? Oder verstehe ich da was falsch?

Gruß, Alex

**Comment by alexanderkartschall** [comment]
Der Adapter funktioniert nicht, ich benutze nun die API v2 von go-e mit den entsprechenden HTTP API keys über diverse Blockly Elemente um den Überschuss zu berechnen und die Wallbox zu steuern.

Gruß, Alex

**Comment by Rollocko** [comment]
Hallo. 
Wenn ich diese Option unter Settings wähle:
„you have implemented your solar power, house Batter or houseConsumption in ioBroker. Connect the devices to this adapter and let the adapter do the job for you“
Wie kann ich dann PV überschussladen aktivieren bzw deaktivieren? Mach ich das dann über den ECO Modus in der go-e App? Weil ich ja will ja nicht zwingend immer diese Option nutzen (z.B. im Winter). 
Jemand eine Idee?
