### ISSUE TITLE
Hardware V2 FW 042.0

### ISSUE THREAD

**Issue by Monox83** [MK-2001/ioBroker.go-e#166]
Moin, der go-e ist nun auf Version 042.0 und der Adapter bringt folgenden Fehler.

`API response validation error: [{"message":"\"lod\" is not allowed","path":["lod"],"type":"object.unknown","context":{"child":"lod","label":"lod","value":65535,"key":"lod"}},{"message":"\"lts\" is not allowed","path":["lts"],"type":"object.unknown","context":{"child":"lts","label":"lts","value":0,"key":"lts"}},{"message":"\"pco\" is not allowed","path":["pco"],"type":"object.unknown","context":{"child":"pco","label":"pco","value":"","key":"pco"}},{"message":"\"cmf\" is not allowed","path":["cmf"],"type":"object.unknown","context":{"child":"cmf","label":"cmf","value":0,"key":"cmf"}},{"message":"\"ath\" is not allowed","path":["ath"],"type":"object.unknown","context":{"child":"ath","label":"ath","value":1200,"key":"ath"}},{"message":"\"psp\" is not allowed","path":["psp"],"type":"object.unknown","context":{"child":"psp","label":"psp","value":11300,"key":"psp"}},{"message":"\"cco\" is not allowed","path":["cco"],"type":"object.unknown","context":{"child":"cco","label":"cco","value":180,"key":"cco"}},{"message":"\"map\" is not allowed","path":["map"],"type":"object.unknown","context":{"child":"map","label":"map","value":123,"key":"map"}},{"message":"\"frm\" is not allowed","path":["frm"],"type":"object.unknown","context":{"child":"frm","label":"frm","value":1,"key":"frm"}},{"message":"\"los\" is not allowed","path":["los"],"type":"object.unknown","context":{"child":"los","label":"los","value":"{\"chg\":[[\"053644\",10,0,1,0,[1,2,3],6]]}","key":"los"}}]`

Grüße Monox

**Comment by matzze2000** [comment]
Kann ich bestätigen, habe genau die gleiche Fehlermeldung seit dem Update auf Version 042.0 (Hardware ist V2). Dachte erst das sind eventuell Felder aus der neuen API V2, aber diese ganzen Werte gibt es dort auch nicht.

**Comment by matzze2000** [comment]
Wie vermutet hat das FW Update da etwas vermurkst. Es gibt auch ein Issue dazu im API Git: https://github.com/goecharger/go-eCharger-API-v1/issues/114

Leider noch keine Info wann es eine Lösung gibt. Temporär bleibt wohl nur dem Support zu schreiben und sich von denen die alte FW zuschicken zu lassen.

**Comment by matzze2000** [comment]
Korrektur: Ich habe gerade gesehen, dass es hier vor 3 Tagen ein Update gab, das noch nicht im stable Zweig von iobroker verfügbar war. Dabei wurden genau die oben gemeldeten Felder der Struktur hinzugefügt. Habe es gerade über git installiert und jetzt funktionieren die Requests an die API wieder korrekt. Das Problem mit dem Setzen des AMX Wertes (amperePV) funktioniert allerdings API Bedingung nach nicht. Ich werde jetzt erst mal wieder auf die alte FW downgraden.

**Comment by Jockelflo** [comment]
Habe heute morgen beide Go-E Charger ebenfalls auf die FW 0.42 gebracht und hatte mit dem Adapter Probleme. Man sollte den Adapter über Git nochmal installieren (1.0.27 von hier über die 1.0.27 in iobroker drüber installieren). Jetzt klappt es wieder
