### ISSUE TITLE
Ich benötige eine kurze Erklärung zum PV-Überschussladen

### ISSUE THREAD

**Issue by FranzKillig** [MK-2001/ioBroker.go-e#168]
Hallo Zusammen,

mir erschließen sich leider die Einstellungen für das PV-Überschussladen nicht ganz, deshalb würde ich mich über eine kurze Erklärung zu folgenden Punkten freuen:

Was bedeutet "onlyACK"?

Unter "ObjektID für die aktuell verfügbare Solarleistung in Watt [W]" wird doch die Gesamtleistung eingetragen die vom Dach kommt, nicht was als Überschuss ins Netz geht, oder?

Wenn bei mir (Huawei-Anlage) beim Laden des Batteriespeichers der Wert positiv und beim Entladen  negativ ist, muss der Wert nicht negiert werden, oder?

Man kann unter "Minimum Akkustand in Wattstunden [Wh]" zwar die Entladegrenze des Batteriespeichers eintragen, aber woher weis der Adapter wie der Ladezustand des Batteriespeichers ist. Oder wird das über die Lade- bzw. Entladeladeleistung hochgerechnet?
Ich denke besser wäre hier die Möglichkeit, wenn man den tatsächlichen Ladezustand des Batteriespeichers angeben könnte.

Würde mich sehr freuen, wenn sich jemand die Zeit nimmt, mich zu erleuchten.

Gruß
Franz

**Comment by MK-2001** [comment]
Hallo, 
OnlyAck:
ACK (Acknowledgement) ist ein Status Attribut von ioBroker. Werte können bestätigt (ack = true) oder unbestätigt sein (ack = false).
Normalerweise sollten von einem System immer nur bestätigte Werte geliefert werden. Unbestätigte werden zu steuern verwendet und dann vom Zielgerät nachträglich bestätigt.
Je nachdem welchen Adapter du verwendest, kommen ggf. auch unbestätigte werte aus dem Adapter zurück, dann muss der Haken bei OnlyAck raus. 
Mehr information dazu:
Im Forum: https://forum.iobroker.net/topic/32275/ack-state-abfragen-lesen/3
oder auf den Adapter Seiten: https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#on---subscribe-on-changes-or-updates-of-some-state 

"ObjectID of ..."
Hier muss kein statischer Wert eingetragen werden, sondern die ioBroker Object ID des Systems. Diese sieht meistens so aus: "<Adaptername>.0.<Gerät>.<Attribut>". der Go-E Adapter holt sich dann informationen von diesem Objekt bzw. lässt sich durch den anderen Adapter aktualisieren. 
Beispiele sind hier:
https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#on---subscribe-on-changes-or-updates-of-some-state 
In dem Feld steht dann drin was in der Spalte "Foreign Adapter Attribute" beschreiben ist. Dieses Objekt kann dann den Wert haben wir in "Example Value" dargestellt.

Negieren:
Vergleiche es am besten mit den Werten wie in den Beispielen oben dargestellt. Wenn du entsprechend andere Werte hast, muss du den Wert negieren.

**Comment by MK-2001** [comment]
Bitte die Diskussionsseiten nutzen.
