### ISSUE TITLE
	this.translationObjectV2.keys is not a function

### ISSUE THREAD

**Issue by arteck** [MK-2001/ioBroker.go-e#169]
```
2023-07-21 06:47:13.166 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | --
go-e.0 | 2023-07-21 06:47:13.154 | error | this.translationObjectV2.keys is not a function
go-e.0 | 2023-07-21 06:47:13.153 | error | TypeError: this.translationObjectV2.keys is not a function at GoE.getStateFromDevice (/opt/iobroker/node_modules/iobroker.go-e/main.js:331:76) at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:126:20) at GoE.emit (node:events:513:28) at GoE.emit (node:domain:489:12) at GoE._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9030:18) at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9008:26
go-e.0 | 2023-07-21 06:47:13.151 | error | unhandled promise rejection: this.translationObjectV2.keys is not a function
go-e.0 | 2023-07-21 06:47:13.149 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
host.iobroker | 2023-07-21 06:47:11.887 | info | instance system.adapter.go-e.0 started with pid 46410

```

**Comment by arteck** [comment]
![grafik](https://github.com/MK-2001/ioBroker.go-e/assets/6681528/e796f8f1-fc52-4983-b6f1-3dfeff47fec5)

**Comment by Transalpler71** [comment]
I get the same Message in Use of a V4 HW with Version 1.0.27
`<html>
<body>


go-e.0 | 2023-08-24 17:08:53.810 | info | terminating
-- | -- | -- | --
go-e.0 | 2023-08-24 17:08:53.791 | error | this.translationObjectV2.keys is not a function
go-e.0 | 2023-08-24 17:08:53.791 | error | TypeError: this.translationObjectV2.keys is not a function at GoE.getStateFromDevice (/opt/iobroker/node_modules/iobroker.go-e/main.js:331:76) at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:126:20) at GoE.emit (node:events:513:28) at GoE.emit (node:domain:489:12) at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8232:26
go-e.0 | 2023-08-24 17:08:53.789 | error | unhandled promise rejection: this.translationObjectV2.keys is not a function
go-e.0 | 2023-08-24 17:08:53.789 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
go-e.0 | 2023-08-24 17:08:53.774 | warn | Sentry enabled. You can switch it off in settings of the adapter.


</body>
</html>`
