### ISSUE TITLE
API response validation error

### ISSUE THREAD

**Issue by allesclip** [MK-2001/ioBroker.go-e#171]
Hallo,

nach dem Firmwareupdate meines go E-Chargers auf Firmware 042.0 bekomme ich zwar eine Verbindung, aber auch folgende Meldung:

API response validation error: [{"message":"\"lod\" is not allowed","path":["lod"],"type":"object.unknown","context":{"child":"lod","label":"lod","value":65535,"key":"lod"}},{"message":"\"lts\" is not allowed","path":["lts"],"type":"object.unknown","context":{"child":"lts","label":"lts","value":0,"key":"lts"}},{"message":"\"pco\" is not allowed","path":["pco"],"type":"object.unknown","context":{"child":"pco","label":"pco","value":"","key":"pco"}},{"message":"\"cmf\" is not allowed","path":["cmf"],"type":"object.unknown","context":{"child":"cmf","label":"cmf","value":0,"key":"cmf"}},{"message":"\"ath\" is not allowed","path":["ath"],"type":"object.unknown","context":{"child":"ath","label":"ath","value":1200,"key":"ath"}},{"message":"\"psp\" is not allowed","path":["psp"],"type":"object.unknown","context":{"child":"psp","label":"psp","value":11300,"key":"psp"}},{"message":"\"cco\" is not allowed","path":["cco"],"type":"object.unknown","context":{"child":"cco","label":"cco","value":180,"key":"cco"}},{"message":"\"map\" is not allowed","path":["map"],"type":"object.unknown","context":{"child":"map","label":"map","value":123,"key":"map"}},{"message":"\"frm\" is not allowed","path":["frm"],"type":"object.unknown","context":{"child":"frm","label":"frm","value":1,"key":"frm"}},{"message":"\"los\" is not allowed","path":["los"],"type":"object.unknown","context":{"child":"los","label":"los","value":"{\"chg\":[[\"053644\",10,0,1,0,[1,2,3],6]]}","key":"los"}}]

Gibt es hierzu eine Lösung?

VG

**Comment by McGlenWin** [comment]
Ich bin leider auch in die Update Falle getappt.
Habe die gleiche Fehlermeldung.
Die Objekte werden nicht mehr aktualisiert.
Über eine Lösung wäre ich sehr dankbar!

**Comment by Enno-von-Schwerin** [comment]
gleicher Fehler hier.
Leider auch geupdatet und bekomme nun auch diesen Fehler.

**Comment by McGlenWin** [comment]
Hi,
ich habe bei go-e ein downgrade beantragt.
Nach Zusendung der Seriennr. haben sie mir die Datei zugesendet und ich
konnte den Downgrade erfolgreich durchführen. Nun läuft es wieder. Der
Fehler ist bekannt, er sollte mit dem nächsten Firmwareupdate behoben
werden.

Gruß

Markus

Am Di., 3. Okt. 2023 um 00:38 Uhr schrieb Enno-von-Schwerin <
***@***.***>:

**Comment by jdrescher2006** [comment]
Ich habe auch ein Validierungs-Problem. Ich hab die FW Version 055.0, Hardware V3. Wenn ich den Adapter auf V2 einstelle, stürzt er komplett ab, oder startet gar nicht erst.
Bei Nutzung der API V1 gibt es dann den Validierungsfehler:
API response validation error: [{"message":"\"tme\" with value \"0302-300526\" fails to match the required pattern: /^[0-9]{10}$/","path":["tme"],"type":"string.pattern.base","context":{"regex":{},"value":"0302-300526","label":"tme","key":"tme"}}]

Der tme Wert passt aber auch überhaupt nicht. Vielleicht versuche ich auch mal eine ältere Firmware.
