### ISSUE TITLE
ID „go-e.0.loaded_energy_kwh“ um den Faktor 1000 zu hoch

### ISSUE THREAD

**Issue by maxe1111** [MK-2001/ioBroker.go-e#18]
Hi,

möglicherweise ein kleiner Schönheitsfehler: 

Unter Objekte - go-e.0 gibt es die ID „go-e.0.loaded_energy_kwh“. Der Wert steht für die bereits ins Auto geladene Energie und wird auch von der Original go-eCharger App (in kWh) angezeigt.

Der Wert in „go-e.0.loaded_energy_kwh“ ist allerdings nicht der Wert in kWh, sondern in Wh, also Faktor 1000 zu hoch. Oder kann ich das irgendwo konfigurieren ?

Gruss
maxe1111

**Comment by MK-2001** [comment]
Mhhh. Ich werde das beim nächsten laden beobachten :-) Und ggf. korrigieren.

**Comment by maxe1111** [comment]
Ich lade gleich mal ... und häng einen Screenshot an

**Comment by MK-2001** [comment]
Stimmt. Wird mit der nächsten Version erledigt. Danke dir fürs melden!

**Comment by maxe1111** [comment]
Klasse! Danke, dass du deine Freizeit hierfür opferst!
