### ISSUE TITLE
Geladene ​Energiemenge pro RFID Karte​ in kWh (eca) um Faktor 10 zu hoch

### ISSUE THREAD

**Issue by ChrisBGL** [MK-2001/ioBroker.go-e#20]
Hallo,

die Energiemenge der RFID Karte wird in der App mit z.B. 20 kWh angezeigt, im Adapter allerdings mit 200.

**Comment by MK-2001** [comment]
Hallo. Ich habe das nun bei mir in der Version 0.20 nicht nachstellen können. Kannst du mir einen Status zukommen lassen aus dem Debug?

**Comment by ChrisBGL** [comment]
Ja genau, der Status zeigt 1580, die App 158 kWh.

Habe aber gerade das Update auf die Version 1.0 gemacht, jetzt zeigt auch der Datenpunkt 158.
