### ISSUE TITLE
add mqtt connection

### ISSUE THREAD

**Issue by arteck** [MK-2001/ioBroker.go-e#207]
die Box erlaubt eine mqtt connection..
kannst du den adapter umstellen so das man auswählen kann auf polling oder mqtt 

der mqtt publisht die Änderungen sofort..

**Comment by MK-2001** [comment]
Bisher sehe ich kein Aufwand Nutzen Vergleich.
Ich denke nicht das ich dies in den kommenden Monaten umsetzen kann, rein zeitlich.

**Comment by MK-2001** [comment]
Duplicate to #161
