### ISSUE TITLE
Fehler im LOG

### ISSUE THREAD

**Issue by Stoimie** [MK-2001/ioBroker.go-e#22]
ich bekomme wiederholt Fehlermeldungen im Log, ansonsten scheint der Adapter aber zu funktionieren

Log ist angerhangen
[go-e Fehler-Log.txt](https://github.com/MK-2001/ioBroker.go-e/files/5753968/go-e.Fehler-Log.txt)

**Comment by MK-2001** [comment]
Hallo Stoimie.

Danke für die Info. 
Kannst du bitte für die Log das Debug aktivieren? 
Ich kann noch nicht erkennen warum er auf einen Fehler läuft.

Ich werde in einer Version es einbauen, dass Fehler abgefangen werden, da hier scheinbar das Modul andauernd neu gestartet wird.

Gruß

**Comment by MK-2001** [comment]
Wird in 1.0.3 behoben. Dies ist nun verfügbar auf der latest.

**Comment by MK-2001** [comment]
Ich das Thema müsste abgefangen sein. Andernfalls bitte einfach wieder auf machen.
