### ISSUE TITLE
Update to 1.0.32 to 1.0.34 failes

### ISSUE THREAD

**Issue by Horgul123** [MK-2001/ioBroker.go-e#235]
I'm on V1.0.32 and can update to 1.0.34. js-controller and admin are on the latest beta version
Update is not successfull:

`$ iobroker upgrade go-e@1.0.34 --debug

Update go-e from @1.0.32 to @1.0.34

NPM version: 10.7.0

Installing iobroker.go-e@1.0.34... (System call)

npm warn ERESOLVE overriding peer dependency

npm warn While resolving: @mui/x-date-pickers@7.6.1npm warn Found: @mui/material@5.14.14npm warn node_modules/@iobroker/adapter-react-v5/node_modules/@mui/materialnpm warn @mui/material@"5.14.14" from @iobroker/adapter-react-v5@4.14.1npm warn node_modules/@iobroker/adapter-react-v5npm warn @iobroker/adapter-react-v5@"^4.13.13" from iobroker.radar-trap@2.2.0npm warn node_modules/iobroker.radar-trapnpm warnnpm warn Could not resolve dependency:npm warn peer @mui/material@"^5.15.14" from @mui/x-date-pickers@7.6.1npm warn node_modules/@iobroker/adapter-react-v5/node_modules/@mui/x-date-pickersnpm warn @mui/x-date-pickers@"^7.5.1" from @iobroker/adapter-react-v5@4.14.1npm warn node_modules/@iobroker/adapter-react-v5npm warnnpm warn Conflicting peer dependency: @mui/material@5.15.20npm warn node_modules/@mui/materialnpm warn peer @mui/material@"^5.15.14" from @mui/x-date-pickers@7.6.1npm warn node_modules/@iobroker/adapter-react-v5/node_modules/@mui/x-date-pickersnpm warn @mui/x-date-pickers@"^7.5.1" from @iobroker/adapter-react-v5@4.14.1npm warn node_modules/@iobroker/adapter-react-v5

npm warn ERESOLVE overriding peer dependencynpm warn While resolving: @mui/x-date-pickers@7.6.1npm warn Found: @mui/material@5.14.14npm warn node_modules/@iobroker/json-config/node_modules/@mui/materialnpm warn @mui/material@"5.14.14" from @iobroker/adapter-react-v5@5.0.2npm warn node_modules/@iobroker/json-config/node_modules/@iobroker/adapter-react-v5npm warn @iobroker/adapter-react-v5@"^5.0.0" from @iobroker/json-config@6.17.15npm warn node_modules/@iobroker/json-confignpm warnnpm warn Could not resolve dependency:npm warn peer @mui/material@"^5.15.14" from @mui/x-date-pickers@7.6.1npm warn node_modules/@iobroker/json-config/node_modules/@mui/x-date-pickersnpm warn @mui/x-date-pickers@"^7.5.1" from @iobroker/adapter-react-v5@5.0.2npm warn node_modules/@iobroker/json-config/node_modules/@iobroker/adapter-react-v5

npm error code ETARGET

npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-06-17T11_27_31_995Z-debug-0.log

upload [9] go-e.admin /opt/iobroker/node_modules/iobroker.go-e/admin/admin.d.ts admin.d.ts video/mp2t

upload [0] go-e.admin /opt/iobroker/node_modules/iobroker.go-e/admin/words.js words.js application/javascript

Process exited with code 0`

**Comment by fuchs-1978** [comment]
1.0.35 Same Problem here

**Comment by Horgul123** [comment]
Update from 1.0.32 to 1.0.35 works, version number seems to be OK.
