### ISSUE TITLE
Go-e does not start

### ISSUE THREAD

**Issue by Horgul123** [MK-2001/ioBroker.go-e#239]
V1.0.35

Go-e instance is not starting, it tells me that Api V2 is not activated, but it is. (See screenshot)

Log:

`<html>
<body>

go-e.0 | 2024-06-18 15:00:19.288 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
go-e.0 | 2024-06-18 15:00:19.287 | info | terminating
go-e.0 | 2024-06-18 15:00:19.271 | error | Api V2 is not enabled
go-e.0 | 2024-06-18 15:00:19.271 | error | Error: Api V2 is not enabled at GoE.setValueV2 (/opt/iobroker/node_modules/iobroker.go-e/main.js:719:35) at GoE.onReady (/opt/iobroker/node_modules/iobroker.go-e/main.js:101:18) at GoE.emit (node:events:517:28) at GoE._callReadyHandler (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6343:12) at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:6328:14
go-e.0 | 2024-06-18 15:00:19.270 | error | unhandled promise rejection: Api V2 is not enabled
go-e.0 | 2024-06-18 15:00:19.269 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
go-e.0 | 2024-06-18 15:00:19.251 | info | Calculation Method: iob
go-e.0 | 2024-06-18 15:00:19.250 | info | Intervall: 60
go-e.0 | 2024-06-18 15:00:19.250 | info | Server: go-eCharger.fritz.box
go-e.0 | 2024-06-18 15:00:19.250 | info | Adapter is staring in Version setByGitHubActions
go-e.0 | 2024-06-18 15:00:19.237 | info | starting. Version 1.0.35 in /opt/iobroker/node_modules/iobroker.go-e, node: v18.20.3, js-controller: 6.0.5

</body>
</html>`

![WhatsApp Image 2024-06-18 at 15 03 02](https://github.com/MK-2001/ioBroker.go-e/assets/45976162/507c47eb-6af5-48b3-9a9e-7e031e5c7f98)

**Comment by Dax88** [comment]
The API V2 has to be activated in the Instance Settings: 
![image](https://github.com/MK-2001/ioBroker.go-e/assets/30949269/d59aeb8c-0e25-495d-acf6-809b7a9f6746)

**Comment by Horgul123** [comment]
Was fixed in 1.0.36 :)
