### ISSUE TITLE
PV-Überschussladen funktioniert mit Go-E-Berechnung nicht

### ISSUE THREAD

**Issue by Dax88** [MK-2001/ioBroker.go-e#240]
Hallo,
ich habe nun mit der 1.0.35 testweise die Berechnung auf go-e-Hardware gestellt. Die pGrid-Werte werden auch brav aktualisiert: 

`Wrote ids Object: {"pGrid":7694,"pAkku":0} with response {"ids":true}`

Aber die Go-E-App sagt mir weiterhin "PV-Überschuss nicht verfügbar"
![image](https://github.com/MK-2001/ioBroker.go-e/assets/30949269/d1e5ae3c-3069-4fdd-bd8b-2ec7613379d3)

**Comment by Dax88** [comment]
Ok hab den Fehler schon selbst gefunden - pGrid muss natürlich Negativ sein...

**Comment by BenjaminK87** [comment]
Wie genau kann man die Werte schreiben? Ich hatte danach gesucht, aber nicht gefunden. Würde mich über eine Antwort freuen.

**Comment by MK-2001** [comment]
Der Adapter holt sich die Daten aus angegeben Objekten.
Die kannst du in den Einstellungen festlegen.
