### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [MK-2001/ioBroker.go-e#250]
ERRORs must be fixed:

❗ [E026] "{'engines': {'node'>='16'}}" is required at [package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/package.json), "{'engines':{'node'>='18'}}" is recommened
 ❗ [E033] @iobroker/adapter-core 2.6.0 specified. 3.1.4 is required as minimum, 3.1.6 is recommended. Please update dependencies at [package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/package.json)
 ❗ [E036] @iobroker/testing 2.4.5 specified. 4.1.3 is required as minimum, 4.1.3 is recommended. Please update devDependencies at [package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/package.json)
 ❗ [E130] Too many "common.news" found in [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json). Must be less than 20. Please remove old news.
 ❗ [E204] Version(s) "0.9.0" listed at common.news at [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json) do not exist at [NPM](https://www.npmjs.com/package/iobroker.go-e). Please remove from news.

WARNINGs should be fixed if time allows:

 👀 [E145] Missing mandatory translation into de of some "common.news" in [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json).
 👀 [W040] "keywords" within [package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/package.json) should contain "ioBroker"
 👀 [W115] "common.tier" is required in [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json). Please check https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#adapter.
 👀 [W145] Missing suggested translation into ru,pt,nl,fr,it,es,pl,uk,zh-cn of some "common.news" in [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json).
 👀 [W181] "common.license" in [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json) is deprecated. Please define object "common.licenseInformation"
 👀 [W184] "common.main" is deprecated and ignored. Please remove from [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json). Use "main" at [package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/package.json) instead.
 👀 [W184] "common.materialize" is deprecated for admin >= 5 at [io-package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/io-package.json). Please use property "adminUI".
 👀 [W522] Please consider migrating to admin 5 UI (jsonConfig).
 👀 [W853] .npmignore found - consider using [package.json](https://github.com/MK-2001/ioBroker.go-e/blob/master/package.json) object "files" instead.

**Please feel free to ask if any questions arise.**

**Comment by MK-2001** [comment]
Waiting for PR

**Comment by mcm1957** [comment]
Where do you need halp to solve which problem?

**Comment by MK-2001** [comment]
I thought it is described in the issue?

**Comment by mcm1957** [comment]
repleaced by #253
