### ISSUE TITLE
Please fix testing

### ISSUE THREAD

**Issue by mcm1957** [MK-2001/ioBroker.go-e#259]
Please fix standard Github testing.
Node 16 is outdated for a long time. At least node 16 must be removed and test must be done using node 18 / 20 / 22.

Please let us know if you need any help to adjust tests.

Note:
Future releases might be blocked from repositories if standard testing is not working.

![image](https://github.com/user-attachments/assets/d6b13ccf-ec75-45ed-95cb-840c2ea6e321)

**Comment by MK-2001** [comment]
I'ld like to say that is file is maybe coming from the adapter test 
![image](https://github.com/user-attachments/assets/2fad52e4-c915-436f-a72e-cc7f0c674dc4)

Please advise who to solve this testing issue.

**Comment by MK-2001** [comment]
Hello @mcm1957 
May you can help here?

**Comment by MK-2001** [comment]
Thanks testing is woking now!
