### ISSUE TITLE
changelog 1.0.0

### ISSUE THREAD

**Issue by lobomau76** [MK-2001/ioBroker.go-e#33]
What is different in 1.0.0 in comparison to 0.2.0.?

**Comment by MK-2001** [comment]
Hi. 
Difference are all the changes from 0.2.0 to 1.0.0.
This is documented to the Changelog.

Eher Version 1.0.0 in compare to 0.2.2 is only the publish to the stable repository in ioBroker. 
This I will add to the changeling documentation.

https://github.com/MK-2001/ioBroker.go-e/compare/v0.2.0...master
