### ISSUE TITLE
Wrong date in iobroker

### ISSUE THREAD

**Issue by Wildbill-Z** [MK-2001/ioBroker.go-e#35]
My go-echarger seems to give me a wrong date (today is the 20th of February 2021 14:00. In the json I see "2002211400" for tme which is obviously wrong. That should be "20022**0**1400". I have set "tof":"101","tds":"1" in the go-echarger, which would be correct for timezone Euroe/Berlin I hope.
Nevertheless, in iobroker I see this for the datapoint synctime/tme: Fri Feb 21 2020 14:00:00 GMT+0100 (Mitteleuropäische Normalzeit)
The date is exatly what the go-echarger is delivering, but the weekday is wrong. The 21st should be a Sunday and not Friday. So the go-echarger seems to make a misstake (don't know why, maybe problem with europe.pool.ntp.org? But the adapter also seems to make a misstake by delivering the wrong weekday.

Greetings, Jürgen

**Comment by Wildbill-Z** [comment]
I tested a while and then found the wrong thing. Go-echarger is sending date/time in format ddmmyyhhmm as in API description and as you can see below:
2002211635
That was the value for now, 20st February 2021 16:35
The adapter reads it as yymmddhhmm which results in 20th February 2020 16:35 which was a Friday. 
So you shoud change the adapter reading.

Greetings, Jürgen

**Comment by MK-2001** [comment]
Hi Jürgen, 

thank you. you are complete right! It will be changed in the next version. Kind regards
Marcus

**Comment by andispammonyer** [comment]
Hi,

@MK-2001 thanks a lot for your adapter!!!
By when do you expect this fix?

**Comment by MK-2001** [comment]
It is already in the latest available. I thought I wait until some other features are ready. But currently there is no time on my site... Corona, Lockdown Kindergarden. You know?

**Comment by andispammonyer** [comment]
Sure I can understand you. What do you mean with it's in the latest available? Release 1.0.0?
