### ISSUE TITLE
Neuste Version

### ISSUE THREAD

**Issue by Trunks1982** [MK-2001/ioBroker.go-e#4]
hi die 0.0.2 läuft nicht nach dem installieren.War mal so frei und wollte diese testen.

**Comment by MK-2001** [comment]
Wie installiert du eine neue Version?
Im Git/NPM ist bereits die 0.0.3?
(Ich habe gerade gesehen, dass die Beschreibung für 0.0.3 noch nicht drin war.)

**Comment by Trunks1982** [comment]
Ja hatte 0.0.3 installiert über git.

**Comment by Trunks1982** [comment]
Ok habe jetzt 0.0.4 installiert der läuft.

**Comment by Trunks1982** [comment]
<img width="828" alt="Bildschirmfoto 2020-07-27 um 11 04 36" src="https://user-images.githubusercontent.com/62701386/88523932-03749600-cff9-11ea-91b4-2681fa8c5976.png">

Hast du diesen Fehler bei dir auch schon festgestellt?
Könnte vielleicht aber auch an meinem Script liegen wo er versucht immer die Ladestufe einzustellen obwohl kein Auto angeschlossen ist.

**Comment by MK-2001** [comment]
Hi.

Ich denke er kann bei dir im Netz den go-recharger DNS Namen nicht auflösen. Kannst du mal eine IP-Adresse in den Einstellungen hinterlegen?

**Comment by Trunks1982** [comment]
Ok Ich teste mal.Den Fehler hat er zb beim Laden nicht gehabt.Ging ja so immer, nur er spät natürlich so dann die logfile zu,
