### ISSUE TITLE
Wrong typ nach Umstellung auf js-controller 3.3.4

### ISSUE THREAD

**Issue by mane444** [MK-2001/ioBroker.go-e#40]
Seit dem Update auf js-controller 3.3.4 bringt der Adapter sehr viele Warnmeldungen.

![image](https://user-images.githubusercontent.com/59375254/116785140-3ec85780-aa98-11eb-890c-4fc156e28f77.png)

**Comment by Monox83** [comment]
Moin, nach dem Update auf 1.0.4 ist es besser, jetzt kommt folgende Fehler.


Cloud not store synctime, because of error object null is not iterable (cannot read property Symbol(Symbol.iterator))
--

Grüße Monox

**Comment by lobomau76** [comment]
Ich habe keine Verbesserung/Änderung festgestellt nach update auf 1.0.4:
Ich habe log wieder auf "warn" gestellt. Ansonsten läuft aber alles ohne Probleme.
`



go-e.0 | 2021-05-19 08:14:17.563 | info | (23157) State value to set for "go-e.0.scheduler_double_press" has to be type "number" but received type "string"
-- | -- | -- | --
go-e.0 | 2021-05-19 08:14:17.546 | info | (23157) State value to set for "go-e.0.energy.norway_mode" has to be type "number" but received type "string"
go-e.0 | 2021-05-19 08:14:17.535 | info | (23157) State value to set for "go-e.0.electricity_exchange.balance_time" has to be type "number" but received type "string"
go-e.0 | 2021-05-19 08:14:17.525 | info | (23157) State value to set for "go-e.0.unlock_state" has to be type "number" but received type "string"
go-e.0 | 2021-05-19 08:14:17.514 | info | (23157) State value to set for "go-e.0.settings.color.led_save_energy" has to be type "number" but received type "string"
go-e.0 | 2021-05-19 08:14:17.508 | info | (23157) State value to set for "go-e.0.unlocked_by" has to be type "number" but received type "string"
go-e.0 | 2021-05-19 08:14:17.501 | info | (23157) State value to set for "go-e.0.adapter_in" has to be type "number" but received type "string"
go-e.0 | 2021-05-19 08:14:17.474 | info | (23157) State value to set for "go-e.0.temperatures.maintempereature" has to be type "number" but received type "string"
go-e.0 | 2021-05-19 08:14:17.267 | info | (23157) State value to set for "go-e.0.rfid.badges.10.consumption" has to be type "number" but received type "string"
go-e.0 | 2021-05-19 08:14:17.219 | info | (23157) State value to set for "go-e.0.time_daylight_saving" has to be type "number" but received type "string"
go-e.0 | 2021-05-19 08:14:17.214 | info | (23157) State value to set for "go-e.0.time_offset" has to be type "number" but received type "string"



`

**Comment by MK-2001** [comment]
That issue has not been handled in 1.0.4. It has now handled in 1.0.6 and gets an additional reducements about temperatures in 1.0.7
