### ISSUE TITLE
Ver. 1.0.7/08: API response validation error

### ISSUE THREAD

**Issue by lobomau76** [MK-2001/ioBroker.go-e#54]
Just updated from 1.0.6 to 1.0.7 with the following error now. 
It also continues the info of type number.
After updating from 1.0.7 to 1.0.8 same error, no change:

`

go-e.0 | 2021-06-10 08:44:51.642 | error | (13136) API response validation error: {"_original":{"version":"B","tme":"1006210844","rbc":"41","rbt":"3581078625","car":"1","amp":"8","err":"0","ast":"0","alw":"0","stp":"0","cbl":"20","pha":"8","tm
-- | -- | -- | --
go-e.0 | 2021-06-10 08:44:24.790 | error | (13136) API response validation error: {"_original":{"version":"B","tme":"1006210844","rbc":"41","rbt":"3581051769","car":"1","amp":"8","err":"0","ast":"0","alw":"0","stp":"0","cbl":"20","pha":"8","tm
go-e.0 | 2021-06-10 08:43:51.918 | error | (13136) API response validation error: {"_original":{"version":"B","tme":"1006210843","rbc":"41","rbt":"3581018811","car":"1","amp":"8","err":"0","ast":"0","alw":"0","stp":"0","cbl":"20","pha":"8","t
go-e.0 | 2021-06-10 08:43:24.785 | error | (13136) API response validation error: {"_original":{"version":"B","tme":"1006210843","rbc":"41","rbt":"3580991773","car":"1","amp":"8","err":"0","ast":"0","alw":"0","stp":"0","cbl":"20","pha":"8","t
go-e.0 | 2021-06-10 08:42:51.631 | error | (13136) API response validation error: {"_original":{"version":"B","tme":"1006210842","rbc":"41","rbt":"3580958622","car":"1","amp":"8","err":"0","ast":"0","alw":"0","stp":"0","cbl":"20","pha":"8","t
go-e.0 | 2021-06-10 08:42:43.768 | info | (13136) State value to set for "go-e.0.settings.ampere_level5" has to be type "number" but received type "string"
go-e.0 | 2021-06-10 08:42:43.732 | info | (13136) State value to set for "go-e.0.settings.ampere_level4" has to be type "number" but received type "string"
go-e.0 | 2021-06-10 08:42:43.723 | info | (13136) State value to set for "go-e.0.settings.ampere_level3" has to be type "number" but received type "string"
go-e.0 | 2021-06-10 08:42:43.674 | info | (13136) State value to set for "go-e.0.settings.ampere_level2" has to be type "number" but received type "string"
go-e.0 | 2021-06-10 08:42:43.658 | info | (13136) State value to set for "go-e.0.settings.ampere_level1" has to be type "number" but received type "string"
go-e.0 | 2021-06-10 08:42:43.652 | info | (13136) State value to set for "go-e.0.settings.color.led_brightness" has to be type "number" but received type "string"
go-e.0 | 2021-06-10 08:42:43.646 | info | (13136) State value to set for "go-e.0.serial_number" has to be type "number" but received type "string"

`

**Comment by jlegen** [comment]
same here - i went back to 1.0.4...

**Comment by MK-2001** [comment]
I will do a solution for the "info" lines as well..

**Comment by MK-2001** [comment]
provided version 1.0.9 (Please update the error message here. Thanks in advance

**Comment by jlegen** [comment]
Hi, the error with 1.0.7/8 was:

2021-06-09 21:08:24.669  - ESC[31merrorESC[39m: go-e.0 (25320) API response validation error: {"_original":{"version":"B","tme":"0906212108","rbc":"7","rbt":"2097600077","car":"1","amp":"16","err":"0","ast":"0","alw":"1","stp":"0","cbl":"0","pha":"56","tmp":"38","tma":[27.38,25.88,25.88,26.63],"amt":"32","dws":"0","dwo":"0","adi":"0","uby":"0","eto":"0","wst":"3","txi":"0","nrg":[224,226,226,1,0,0,0,0,0,0,0,0,0,0,0,0],"fwv":"040.0","sse":"040xxx","wss":"WIFI","wke":"*********************","wen":"1","cdi":"0","tof":"101","tds":"1","lbr":"255","aho":"3","afi":"7","azo":"1","ama":"32","al1":"10","al2":"16","al3":"0","al4":"0","al5":"0","cid":"255","cch":"65535","cfi":"65280","lse":"1","ust":"0","wak":"11f336fc8e","r1x":"2","dto":"0","nmo":"0","sch":"AAAAAAAAAAAAAAAA","sdp":"0","eca":"0","ecr":"0","ecd":"0","ec4":"0","ec5":"0","ec6":"0","ec7":"0","ec8":"0","ec9":"0","ec1":"0","rca":"04C17B62","rcr":"","rcd":"","rc4":"","rc5":"","rc6":"","rc7":"","rc8":"","rc9":"","rc1":"","rna":"","rnm":"","rne":"","rn4":"","rn5":"","rn6":"","rn7":"","rn8":"","rn9":"","rn1":"","loe":0,"lot":0,"lom":0,"lop":0,"log":"","lon":0,"lof":0,"loa":0,"lch":0,"mce":0,"mcs":"test.mosquitto.org","mcp":1883,"mcu":"","mck":"","mcc":0},"details":[{"message":"\"rcr\" is not allowed to be empty","path":["rcr"],"type":"string.empty","context":{"label":"rcr","value":"","key":"rcr"}}]}

"rcr" is missing?

**Comment by MK-2001** [comment]
Right. 
I made rcd and rca optional (That are the labels of id-cards.)
Thank you for reporting that bug.

Solved in 1.0.10

**Comment by rglt** [comment]
I have this error with version 1.0.13
<html><body>


go-e.0 | 2021-06-29 21:56:30.887 | info | (27375)  {"version":"B","tme":"2906212156","rbc":"9","rbt":"621827761","car":"1","amx":"0","amp":"12","err":"0","ast":"0","alw":"0","stp":"0","cbl":"32","pha":"56","fsp":"0","tma":[19.625,25.25],"dws"
-- | -- | -- | --
go-e.0 | 2021-06-29 21:56:30.886 | error | (27375) API response validation error: [{"message":"\"tmp\" is  required","path":["tmp"],"type":"any.required","context":{"label":"tmp","key":"tmp"}},{"message":"\"txi\"  is required","path":["txi"],"t
go-e.0 | 2021-06-29 21:55:30.899 | info | (27375)  {"version":"B","tme":"2906212155","rbc":"9","rbt":"621767772","car":"1","amx":"0","amp":"12","err":"0","ast":"0","alw":"0","stp":"0","cbl":"32","pha":"56","fsp":"0","tma":[19.625,25.25],"dws"
go-e.0 | 2021-06-29 21:55:30.898 | error | (27375) API response validation error: [{"message":"\"tmp\" is  required","path":["tmp"],"type":"any.required","context":{"label":"tmp","key":"tmp"}},{"message":"\"txi\"  is required","path":["txi"],"t
go-e.0 | 2021-06-29 21:54:30.887 | info | (27375)  {"version":"B","tme":"2906212154","rbc":"9","rbt":"621707762","car":"1","amx":"0","amp":"12","err":"0","ast":"0","alw":"0","stp":"0","cbl":"32","pha":"56","fsp":"0","tma":[19.625,25.25],"dws"
go-e.0 | 2021-06-29 21:54:30.886 | error | (27375) API response validation error: [{"message":"\"tmp\" is  required","path":["tmp"],"type":"any.required","context":{"label":"tmp","key":"tmp"}},{"message":"\"txi\"  is required","path":["txi"],"t


</body>
</html>

**Comment by MK-2001** [comment]
Hi the solution is provided here: https://github.com/MK-2001/ioBroker.go-e/discussions/68#discussioncomment-919056
