### ISSUE TITLE
1.0.10 still a lot of info

### ISSUE THREAD

**Issue by lobomau76** [MK-2001/ioBroker.go-e#57]
Version 1.0.10 works fine, but still too much info:

`

go-e.0 | 2021-06-11 08:33:05.962 | info | (22345) State value to set for "go-e.0.settings.color.led_brightness" has to be type "number" but received type "string"
-- | -- | -- | --
go-e.0 | 2021-06-11 08:33:05.847 | info | (22345) State value to set for "go-e.0.firmware_version" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.828 | info | (22345) State value to set for "go-e.0.max_ampere" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.784 | info | (22345) State value to set for "go-e.0.electricity_exchange.price_zone" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.766 | info | (22345) State value to set for "go-e.0.electricity_exchange.finish_hour" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.747 | info | (22345) State value to set for "go-e.0.electricity_exchange.min_hours" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.670 | info | (22345) State value to set for "go-e.0.loaded_energy" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.650 | info | (22345) State value to set for "go-e.0.http_flags" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.628 | info | (22345) State value to set for "go-e.0.cloud_disabled" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.619 | info | (22345) State value to set for "go-e.0.wifi.enabled" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.576 | info | (22345) State value to set for "go-e.0.transmit_interface" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.562 | info | (22345) State value to set for "go-e.0.wifi.state" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.533 | info | (22345) State value to set for "go-e.0.cable_ampere_code" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:05.011 | info | (22345) State value to set for "go-e.0.phases" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:04.997 | info | (22345) State value to set for "go-e.0.stop_state" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:04.945 | info | (22345) State value to set for "go-e.0.allow_charging" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:04.924 | info | (22345) State value to set for "go-e.0.access_state" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:04.890 | info | (22345) State value to set for "go-e.0.error" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:04.868 | info | (22345) State value to set for "go-e.0.ampere" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:04.841 | info | (22345) State value to set for "go-e.0.car" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:04.793 | info | (22345) State value to set for "go-e.0.reboot_timer" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 08:33:04.749 | info | (22345) State value to set for "go-e.0.reboot_counter" has to be type "number" but received type "string"

`

**Comment by MK-2001** [comment]
Thanks a lot for identification. 
I did an update that should reduce the info messages again. 

Please reopen the issue, if there is still throwing info messages.

**Comment by lobomau76** [comment]
I have installed 1.0.10 again. I have also deleted the states before, but I still have the info:
`



go-e.0 | 2021-06-11 11:36:55.928 | info | (28142) State value to set for "go-e.0.settings.color.led_brightness" has to be type "number" but received type "string"
-- | -- | -- | --
go-e.0 | 2021-06-11 11:36:55.915 | info | (28142) State value to set for "go-e.0.firmware_version" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.907 | info | (28142) State value to set for "go-e.0.max_ampere" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.883 | info | (28142) State value to set for "go-e.0.electricity_exchange.price_zone" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.876 | info | (28142) State value to set for "go-e.0.electricity_exchange.finish_hour" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.866 | info | (28142) State value to set for "go-e.0.electricity_exchange.min_hours" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.842 | info | (28142) State value to set for "go-e.0.loaded_energy" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.834 | info | (28142) State value to set for "go-e.0.http_flags" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.815 | info | (28142) State value to set for "go-e.0.cloud_disabled" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.810 | info | (28142) State value to set for "go-e.0.wifi.enabled" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.788 | info | (28142) State value to set for "go-e.0.transmit_interface" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.781 | info | (28142) State value to set for "go-e.0.wifi.state" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.758 | info | (28142) State value to set for "go-e.0.cable_ampere_code" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.576 | info | (28142) State value to set for "go-e.0.phases" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.554 | info | (28142) State value to set for "go-e.0.stop_state" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.546 | info | (28142) State value to set for "go-e.0.allow_charging" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.511 | info | (28142) State value to set for "go-e.0.access_state" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.438 | info | (28142) State value to set for "go-e.0.error" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.413 | info | (28142) State value to set for "go-e.0.ampere" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.387 | info | (28142) State value to set for "go-e.0.car" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.378 | info | (28142) State value to set for "go-e.0.reboot_timer" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.365 | info | (28142) State value to set for "go-e.0.reboot_counter" has to be type "number" but received type "string"
go-e.0 | 2021-06-11 11:36:55.159 | warn | (28142) Sentry enabled. You can switch it off in settings of the adapter.
go-e.0 | 2021-06-11 11:36:55.158 | info | (28142) Intervall: 30
go-e.0 | 2021-06-11 11:36:55.153 | info | (28142) Server: 192.168.1.45
go-e.0 | 2021-06-11 11:36:55.104 | info | (28142) starting. Version 1.0.10 in /opt/iobroker/node_modules/iobroker.go-e, node: v12.22.1, js-controller: 3.3.11



`

**Comment by MK-2001** [comment]
Commit it not publish. There is one more topic what have to be solved and coming in version 1.0.11.
Github will close this issue after it has been published automatic. :-)
