### ISSUE TITLE
Weiterhin Fehler mit Hardware v3 und 1.0.14

### ISSUE THREAD

**Issue by amnesia106** [MK-2001/ioBroker.go-e#62]
Folgender Log Eintrag in iobroker nach starten des Adapters.

go-e.0 | 2021-06-19 15:24:05.144 | info | (75464) {"version":"B","tme":"1906211524","rbc":"15","rbt":"26998952","car":"1","amx":"16","amp":"16","err":"0","ast":"0","alw":"1","stp":"0","cbl":"20","pha":"56","fsp":"0","tma":[33.25,38.875],"dws
-- | -- | -- | --
go-e.0 | 2021-06-19 15:24:05.144 | error | (75464) API response validation error: [{"message":"\"lon\" is required","path":["lon"],"type":"any.required","context":{"label":"lon","key":"lon"}}]

**Comment by MK-2001** [comment]
Danke für das melden des Fehlers. Dieser sollte nun in der 1.0.15 behoben sein.

Gruß
