### ISSUE TITLE
Phases show unexpected results

### ISSUE THREAD

**Issue by dotcom84** [MK-2001/ioBroker.go-e#73]
For my v3 HomeFix 11kW I get unexpected values here:

63 for 3 phases
59 for 1 phase

I'd expect 1 or 3.

<img width="1349" alt="Bildschirmfoto 2021-07-29 um 06 34 43" src="https://user-images.githubusercontent.com/477203/127432416-d53fbc25-1e32-431a-9394-78262f4b8f80.png">
<img width="520" alt="Bildschirmfoto 2021-07-29 um 06 34 22" src="https://user-images.githubusercontent.com/477203/127432422-f2b7b052-d36a-4e6e-80dc-736637af96fd.png">

**Comment by MK-2001** [comment]
Hi. 

to see which phases are connected, use the prepared objects `go-e.0.energy.phase1.preContactorActive`, `go-e.0.energy.phase1.postContactorActive` for all three phases. there is the conversion already done.

About the conversion:
`pha`is returing a decimal value. in your case 56. (screenshot) you have to covert it in a first step to binary: https://www.google.de/search?q=56+to+binary  
With the result `0b111000` and now you can use the description above: 0b gives the hint to use binary, ABC is in your case `1` => All phases are connected to your charger  
DEF is `0` that means that currently no phases is routed to your car. 

I hope it solved your problem. If your adapter is bring up unexpected values here please get in contact with the vendor.
