### ISSUE TITLE
Add new possibilities from Adapter Version 3 

### ISSUE THREAD

**Issue by MK-2001** [MK-2001/ioBroker.go-e#74]
**Describe the bug**  
go-e.co created a new Adapter Design and called it "V3". The resulting firmwares are starting with the identifier of "050" and higher. 

Some functionalities:
* Sich phases during loading process
* Loading below 6A
* Mass On-Off

**To Reproduce**  
1. Buy a new Hardware Adapter

** Solution **
To solve this issue a developer needs the new adapter version on his development environment
(In this open source development , that means at his home, as replacement for existing V2 adapter) :-)

**Comment by dotcom84** [comment]
+1 for Phases switching :)

**Comment by Schwunkel** [comment]
Phases switching!

**Comment by Schwunkel** [comment]
for everyone who cant wait for phase-switching within the adapter just use mqtt. The datapoint "psm" shows 1 for single phase and 2 for three phases, mqtt.xxxxx.psm.set can be used for switching.

**Comment by ChrisBGL** [comment]
Phase switching please!

**Comment by MK-2001** [comment]
Without any Hardware I am not able to develop the new functions. I offered to go-e.co to replace my existing V2.

**Comment by Schwunkel** [comment]
> Without any Hardware I am not able to develop the new functions. I offered to go-e.co to replace my existing V2.

I own a v3 so maybe i can assist and provide you the necessary data!?

**Comment by MK-2001** [comment]
Sorry, I am a private Developer. I don't want to sync my and your availability. The sync effort with tests, issues and new code versions is not acceptable without direct access to the hardware.
