### ISSUE TITLE
Mini-Bug Version 1.0.15

### ISSUE THREAD

**Issue by Poddel** [MK-2001/ioBroker.go-e#79]
Es gibt bei mir minütlich eine Fehlermeldung im Log-File:
>>State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"

Ich habe händisch mit allen zu Verfügung stehenden Formaten versucht, die Fehlermeldung zu unterbinden, ging aber nicht. Bei der Anzeige oben ist die Variable auf "Objekt" gesetzt oder im Code:
{
  "_id": "go-e.0.temperatures.tempereatureArray",
  "type": "state",
  "common": {
    "name": "all temperatures (tma)",
    "type": "object",
    "role": "value.temperature",
    "read": true,
    "write": false
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "file": 1636,
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1629193551667
}
Da müsste etwas im Quellcode angepasst werden! 
Danke dafür 

Nachtrag:
Im Log-File des iobrokers findet eine wahre Nachrichtenflut statt - bis der Ladevorgang unterbrochen wird.:
go-e.0 | 2021-08-17 12:13:00.028 | info | Set value 0 of id alw
-- | -- | -- | --
go-e.0 | 2021-08-17 12:12:51.705 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:34.838 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:34.716 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:34.388 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:34.070 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:32.953 | info | 200 with message: OK
go-e.0 | 2021-08-17 12:12:32.845 | info | 200 with message: OK
go-e.0 | 2021-08-17 12:12:32.731 | info | 200 with message: OK
go-e.0 | 2021-08-17 12:12:32.626 | info | 200 with message: OK
go-e.0 | 2021-08-17 12:12:18.691 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:18.645 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:18.535 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:18.176 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:17.659 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:16.516 | info | 200 with message: OK
go-e.0 | 2021-08-17 12:12:16.407 | info | 200 with message: OK
go-e.0 | 2021-08-17 12:12:16.293 | info | 200 with message: OK
go-e.0 | 2021-08-17 12:12:16.151 | info | 200 with message: OK
go-e.0 | 2021-08-17 12:12:16.040 | info | 200 with message: OK
go-e.0 | 2021-08-17 12:12:09.541 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:09.485 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:09.394 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:09.275 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:09.072 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"
go-e.0 | 2021-08-17 12:12:08.494 | info | State value to set for "go-e.0.temperatures.tempereatureArray" has to be stringified but received type "object"

**Comment by FriMatze** [comment]
Kann mich meinem Vorredner anschließen. 

Benutze folgende HW V3 mit Firmware 052.1.

**Comment by MK-2001** [comment]
Hallo,

Das Schreiben kann in den Einstellungen deaktiviert werden. In den letzten Wochen habe ich dazu eine neue Version in Beta eingestellt.
