### ISSUE TITLE
Abschaltung der Automatik

### ISSUE THREAD

**Issue by fighterzg6** [MK-2001/ioBroker.go-e#80]
hallo, wäre es machbar einen Datenpunkt für die Ladeautomatik zu erstellen in dem ich das Script Aktiv bzw Inaktiv schalten kann? 
Wenn ich mal Laden will und das mit voller Leistung zB.

**Comment by MK-2001** [comment]
Was bedeutet denn Skript aktiv inaktiv schalten. Ich fürchte ich benötige noch ein paar details. Vielleicht kannst du auch ein wenig Logik hier notieren.
