### ISSUE TITLE
Gesamt geladene Energiemenge flasch

### ISSUE THREAD

**Issue by robertfraefel** [MK-2001/ioBroker.go-e#92]
Bei mir stimmt der Wert die gesamt geladene Energiemenge (energy_total) nicht mit der Energie Gesamt in der App überein. 
Adapter Version 1.0.15
Firmware-Version Go-E Charger: 041.0

**Comment by MMeinhardt1** [comment]
Hi, bei mir stimmt der Wert unter "Go-e.0.Energy.total" mit der App überein. 
Die Firmware auf deiner Wallbox scheint sehr alt zu sein, vielleicht hilft da ja ein Update. Der Adapter wird vermutlich nur die von der Wallbox gesendeten Werte anzeigen und nicht selber rechnen.

**Comment by robertfraefel** [comment]
Betreffend der Firmware gibt es meines Wissens nichts neueres. 
Was meinst du mit selber rechnen? Ich möchte einfach den selben Wert sehen wie in der APP.

**Comment by MMeinhardt1** [comment]
Hi,
bezüglich der Firmware hier ein Bild (ich habe HW V3)
![image](https://user-images.githubusercontent.com/56205459/140640150-a03723e2-a73a-416e-be09-38ba1958232b.jpeg)

Hier mein Verbrauch,
![image](https://user-images.githubusercontent.com/56205459/140640163-037b425c-ea5a-4d20-ba7d-340488c1fc18.jpeg)
![image](https://user-images.githubusercontent.com/56205459/140640165-708fb66a-47f7-4db1-ac0c-c0e88e91e1d6.jpeg)

Und bezüglich selber rechnen, ich wollte damit nur sagen das der go-e Adapter nicht selber rechnet sondern nur die Werte entgegennimmt die ihm die Wallbox sendet. 

Das ganze war auch nur ne Idee und hätte ja ein Lösungsansatz sein können.

**Comment by robertfraefel** [comment]
Bei mir wird keine neuere Firmware angezeigt.
![Bildschirmfoto 2021-11-07 um 11 10 15](https://user-images.githubusercontent.com/33721995/140640816-037ea4ab-e433-4b93-b8c5-c6177d742a85.png)
Der Go-E schickt auch den richtigen Wert: eto:59070
 
![Screenshot 2021-11-07 at 11 14 58](https://user-images.githubusercontent.com/33721995/140640938-69307b0a-a7e9-4366-a7c8-5b2911e369eb.png)

Nur der Adapter im ioBroker übernimmt das nicht:
![Screenshot 2021-11-07 at 11 18 08](https://user-images.githubusercontent.com/33721995/140641010-83030e2a-7412-445b-9747-b413b1ba166d.png)

**Comment by MMeinhardt1** [comment]
Das mir der Firmware solltest du eventuell mal bei go-e erfragen, die haben nen recht netten und zügigen Support. 

Den von dir angegebenen State habe ich nicht, eventuell ist dieser alt und jetzt an anderer Stelle zu finden. 

Schaue mal ob du diesen hier bei dir findest,

![image](https://user-images.githubusercontent.com/56205459/140641459-8af344d8-c877-41af-936c-50f21b5106b2.jpeg)


Ansonsten mal den Adapter stoppen, alle Objekte vom go-e löschen und anschließend neu starten. Falls du allerdings irgendwelche Objekte loggst oder für andere Dinge verwendest, dann kann es unter Umständen zu Problemen kommen.

**Comment by robertfraefel** [comment]
Habe ich gefunden und dieser Wert stimmt.
Wie kann ich alte, nicht mehr aktuelle Datenpunkte finden und löschen?

**Comment by MMeinhardt1** [comment]
Adapter stoppen, alle Objekte löschen und Adapter wieder starten. Alle benötigen Objekte werden wieder neu erstellt.

**Comment by robertfraefel** [comment]
Und damit kommen nicht die skripte und alles durcheinander weil dann der datenpunkt fehlt?

**Comment by MMeinhardt1** [comment]
Wenn der Datenpunkt weg ist werden die Scripte nicht mehr funktionieren. Allerdings wird das Script ja so oder so nicht richtig funktionieren wenn der Datenpunkt nicht korrekt aktualisiert wird. Datenpunkt im Script anpassen.

**Comment by robertfraefel** [comment]
Sorry, ich meinte die Datenpunkte welche funktioniert haben. Wenn ich diese alle lösche und durch den Adapter wieder neu installiere, finden die Skripte dann diese Datenpunkte wieder?

**Comment by Ilovegym66** [comment]
ja, wenn die Datenpunkte die gleichen Namen / Ordnerstruktur haben, ist das kein Problem.
Nur die History musst du wieder aktivieren, sonst werden keine Daten mehr geloggt, falls du das vorher schon aktiviert hattest.

**Comment by MK-2001** [comment]
Please use the community.

**Comment by robertfraefel** [comment]
Vielen Dank für deine Hilfe!
